# Logging configuration
logging:
  history:
    max: 30 # http://logback.qos.ch/manual/appenders.html#tbrpMaxHistory
    clean-on-start: true # http://logback.qos.ch/manual/appenders.html#tbrpCleanHistoryOnStart
  file:
    name: # Log file name, if not configured application will log to system out
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%30.30(%X{quiz.channel}@%X{pircbotx.server})]){magenta} %clr([%15.15t{14}]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wex"
    file: "%d{HH:mm:ss.SSS} %5p ${PID:- } [%30.30(%X{quiz.channel}@%X{pircbotx.server})] [%t] --- %-40.40logger{39} : %m%n%wex"
  level:
    com.ztomic: trace
    com.ztomic.ircbot.component.PersistenceThreadPoolExecutor: info
    com.ztomic.ircbot.component.pircbotx.CustomThreadedListenerManager: info
    org.pircbotx: trace
    org.hibernate.SQL: info
    
# Database configuration
spring:
  datasource:
    #url: jdbc:h2:mem:test;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    url: jdbc:h2:./irc-bot;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: quizbot
    password: quizbot
    data: data.sql
    initialization-mode: never
  datasourceX:
    url: jdbc:mysql://dev-vm/irc_bot?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Europe/Zagreb
    username: root
    password:
    platform: mysql
  main:
    banner-mode: log
  jackson:
    serialization:
      indent-output: true
  jpa:
    hibernate:
      ddl-auto: update


# ----------------------------------------------------------
# IRC configuration
# ----------------------------------------------------------

irc:
  start-ident: false
  servers:
  - hostname: irc.fpz.hr
    port: 6667
    auto-nick-change: true
    encoding: UTF-8
    name: SparkTest
    nick-serv-password: null
    login: callidus
    real-name: @project.artifactId@ by ztomic, v@project.version@
    max-line-length: 380
    message-limit: 30
    message-limit-interval: 1
    quiz: true
    channels:
    - name: "#quiz"
      language: CROATIAN
      quiz: true
    - name: "#quiz-en"
      language: ENGLISH
      quiz: false

      
msg:
  quiz:
    - language: CROATIAN
      greet-big-players:
      - "Ladies and gentlemen, The Master of the Quizz himself -->"
      - "Ono sto je Luke Skywalker u svemiru, na kvizu je -->"
      - "Tesko je naci boljeg ili bolju nego sto je -->"
      - "Smrtnici poklonite se, eto nam besmrtNi(c)ka -->"
      - "Svi ste mi dragi, ali najdraz[i|a] mi je -->"
      - "Fanfare zasvirajte, prostrite crveni sag, jer eto nama nase[g] -->"
      - "Pozdrav Herkulu medju kvizoznancima! Dobrodos[ao|la]"
      greet-normal-players:
      - "Ah.. znao sam da nam je nesto nedostajalo, to je nas[a]"
      - "Popijmo nesto za dobra stara vremena, dobri stari znance"
      - "Zaboga, pa gdje si tako dugo"
      - "Glagol nedostajati izgubio je znacenje cim je us[ao|la]"
      - "Dobrodos[ao|a] natrag"
      - "Bilo nam je pusto bez tebe"
      - "Sve do prije sekundice, imenica ceznja bila je sinonim za"
      - "Ohoho.. eto stize poznato nam lice po imenu"
      - "Eto nam kamencica koji je nedostajao nasem mozaiku. Pozdrav"
      greet-newbies:
      - "Novi dan, novo lice :) Nadam se da ces se ugodno osjecati na nasem kanalu"
      - "Dobrodos/ao/la u potprostorcic virtualnog prostora gdje se trazi malo znanja. Ugodan boravak"
      - "Eto nam fazana :) Zovite ga"
      - "Oho! Netko nov nam kuca na vrata, a zove se"
      - "Brucosi, stisnite se malo. Eto vam kolege po imenu"
      - "Dobrodos[ao|la]! Zelim ti da nadjes maleni trunak opipljive srece u ovome malenome kutku virtualnog prostora"
      - "Raskomoti se, opusti se, ali napregni vijugice"
      - "Dobrodos/ao/la na kviz. U ovoj sobi trebaju ti samo dobre vijugice i brzi prstici"
      answer-comments:
      - "Moj naklon"
      - "Ljubim rukice"
      - "Svaka cast"
      - "Ide to vama"
      - "Dajte i drugima priliku"
      - "Eh, da ste jos i lijepi kao sto ste pametni"
      - "Izvrsno"
      - "Fenomenalno"
      - "Maestralno"
      - "Genijalnooo"
      - "Duboko, duboko, nema sto"
      - "Hasta la vista baby"
      - "Tako ste neusporedivi"
      - "Bibliofilija je vasa bolest"
      - "Mozak vam je otekao"
      - "Fantazmagorichno"
      - "Hallelujah"
      - "Nevjerojatno"
      - "Fan fan fantastichooo.."

questions:
  loader:
    file: