INSERT INTO `questions` (`language`, `theme`, `question`, `answers`) VALUES
('CROATIAN', 'Aeronautika', 'Kojom brzinom najcesce lebde jedrilice?', '70 km/h'),
('CROATIAN', 'Aforizmi', 'Cuvajte drvece - na njima su zivjeli...?', 'nasi preci'),
('CROATIAN', 'Agronomija', 'Uzgoj svinja.', 'Svinjogojstvo'),
('CROATIAN', 'Akronim', 'HINA.', 'Hrvatska izvjestajna novinska agencija'),
('CROATIAN', 'Akronimi', 'Akronim Medjunarodnog skijaskog saveza.', 'FIS'),
('CROATIAN', 'Aktualno', 'Britanska djevojcica nestala polovicom 2007. u Portugalu, za sto policija naposlijetku okrivljuje njene roditelje?', 'Madeleine McCann'),
('CROATIAN', 'Alpinizam', 'Najtezi vrh u Alpama (4478 m)?', 'Matterhorn\nMonte Cervino'),
('CROATIAN', 'Anagram', 'Dogadaj: "Puno se kaki o mrtvim"?', 'komemorativni skup'),
('CROATIAN', 'Anagrami', '"L O V A K O"', 'Olovka'),
('CROATIAN', 'Anatomija', 'Abdominalna zlijezda u kojoj se razaraju stari eritrociti, te koja sluzi kao rezervoar krvi?', 'slezena'),
('CROATIAN', 'Anegdota', 'Jedan Parizanin se svaki dan uspinjao na Eiffelov toranj jer je to bilo jedino mjesto gdje mu nije stalno...?', 'Bio pred ocima'),
('CROATIAN', 'Anglizmi', 'Drustvene znanosti.', 'Humanities'),
('CROATIAN', 'Animacije', 'Crtani film o maloj vili, cehoslovacke proizvodnje?', 'vila amalka'),
('CROATIAN', 'Animirani film', '"Heraklo" - Heraklov ucitelj?', 'phil\nphiloctetes'),
('CROATIAN', 'Anomalije', 'Pojava vise od 5 prstiju na udovima.', 'polidaktilija'),
('CROATIAN', 'Antonimi', 'Akcija', 'Reakcija'),
('CROATIAN', 'Antropologija', 'Utemeljitelj strukturalizma u antropologiji?', 'Claude Levi-Strauss'),
('CROATIAN', 'Arheologija', 'Broncani anticki kip, izronjen iz losinjskog akvatorija 27.04.1999.g., koji predstavlja grckog atletu u prirodnoj velicini koji poslije utrke struze sol sa svoga tijela, rad Lizipa iz 4.st.pne.', 'Apoksiomen'),
('CROATIAN', 'Arhitektura', '1997. g. u Bilbau je otvorena jedna od najljepsih zgrada na svijetu?', 'Muzej Guggenheim\nGuggenheim Museo\nGuggenheim muzej'),
('CROATIAN', 'Arihetktura', 'Zdarski aritekt svjetskog glasa poznat u nas po Morskim Orguljama i Pozdravu suncu...?', 'Nikola Basic'),
('CROATIAN', 'Arihtektura', 'Sibensku katedralu gradili su Juraj Dalmatinac i ...', 'Nikola Firentinac'),
('CROATIAN', 'Aritektura', 'Najpoznatiji spomenik Maorske aritekture i umjetnosti u Spanjolskoj, dvorac kraj Granade.', 'Alhambra'),
('CROATIAN', 'ASCII kodovi', 'Znak '' ''?', '32'),
('CROATIAN', 'Asocijacija', 'Frigidarij, tepidarij, kaldarij, lakonij.', 'Rimska kupelj'),
('CROATIAN', 'Asocijacije', 'Auto, mesar, kapetan, motika.', 'Kuka'),
('CROATIAN', 'Astrofizika', 'Hipotetska tvorevina u prostorvremenu koja bi mogla posluziti kao precac kroz prostor i vrijeme?', 'crvotocina'),
('CROATIAN', 'Astrologija', 'Ako ste rodjeni 3.5. (jurkijev datum) koji ste horoskopski znak?', 'Bik'),
('CROATIAN', 'Astronautika', 'Americki naziv za Sputnik I?', 'Explorer I'),
('CROATIAN', 'Astronomija', '"Crvena planeta" je drugi naziv za koji planet..?', 'Mars'),
('CROATIAN', 'Atletika', 'Hrvatski rekorder u desetoboju...', 'Josko Vlasic'),
('CROATIAN', 'Auto moto', 'Automobil koji se prodavao s reklamnim sloganom "malo trosi , puno daje"...?', 'Yugo'),
('CROATIAN', 'Automobili', '....... Espace?', 'Renault'),
('CROATIAN', 'Automobilizam', 'Etapna auto-utrka?', 'Reli\nRally'),
('CROATIAN', 'Avijacija', 'Prvi masovno proizveden vojni zrakoplov u Njemackoj 1910.g.', 'Rumpler Taube'),
('CROATIAN', 'Banda', 'Najveca americka zatvorska banda Meksikanaca?', 'Nuestra Familia'),
('CROATIAN', 'Bande', 'Americka bjelacka rasisticka zatvorska banda koja cini oko 1% zatvorske populacije, ali je odgovorna za 26% ubojstava u zatvorskom sustavu?', 'Aryan Brotherhood\nThe Brand\nArijevsko bratstvo'),
('CROATIAN', 'Bankarstvo', 'Novac pozajmljen pod ugovornim uvjetima?', 'Kredit'),
('CROATIAN', 'Biblija', '"X" u "Xmas" oznacava grcku rijec za Krista (Christ), a to je ...?', 'Xristos'),
('CROATIAN', 'Biljke', 'Agresivna alergena biljka - pelud te biljke jedan je od najjacih poznatih alergena.', 'Ambrozija'),
('CROATIAN', 'Bilogija', 'Australska orhideja koja cvjeta ispod zemlje?', 'Rhizantela Rogers'),
('CROATIAN', 'Biologija', '"Biokemijska tvornica" naseg tijela je...?', 'Jetra'),
('CROATIAN', 'Bitke', 'Tromjesecna bitka u II. svj. ratu u kojoj je poginulo 12 000 Amerikanaca i 100 000 Japanaca?', 'Bitka za Okinawu'),
('CROATIAN', 'Bizarno', 'Americka tvrtka koja proizvodi umjetne dijamante od ugljika iz tijela?', 'LifeGem'),
('CROATIAN', 'Bizarnost', 'Argentinac E.Gomez kojega je usmrtila slucajna hrpa metala bio je poznat kao...?', 'Covjek magnet'),
('CROATIAN', 'Bizarnosti', 'Amerikanac A. Heckard je tuzio Michaela Jordana zbog emocionalnih trauma zato sto mu...?', 'Nalikuje'),
('CROATIAN', 'Bonton', 'Nakon odsvirane ili otpjevane drzavne himne se...?', 'Ne pljesce\nNe aplaudira'),
('CROATIAN', 'Bosanska poezija', '"Tako ti je mala moja kad ljubi..."...?', 'Bosanac'),
('CROATIAN', 'Botanika', 'Arboretum obitelji Bombelles u Vinici pokraj Varazdina.', 'Opeka'),
('CROATIAN', 'Casino', 'Koliko cete dobiti ako ste ulozili 50 zetona na dobitnu boju u ruletu?', '100'),
('CROATIAN', 'Citati', '"?ovjek se rodi slobodan, ali je posvuda u okovima."', 'Jean-Jacques Rousseau'),
('CROATIAN', 'Citati/Humor', 'Stipe Mesic: "U Drugom svjetskom ratu Hrvati su..."?', 'Dvaput pobijedili'),
('CROATIAN', 'Crni humor', 'Beogradski izraz za mlade motocikliste.', 'Donatori'),
('CROATIAN', 'Crtani film', 'Andele, andele, y''arriva, y''arriva, yeppa, yeppa....?', 'Speedy Gonzales'),
('CROATIAN', 'Crtici', '"Mislim da sam vidio micu macu"!Kafo fe fove mafa?', 'Silvester'),
('CROATIAN', 'Datum', 'Svjetski dan voda?', '22. ozujak'),
('CROATIAN', 'David Hasselhoff fan club', 'David je burno reagirao kada su ga u Baywatchu zamolili da? :)', 'depilira prsa'),
('CROATIAN', 'Deminutiv', 'Kost', 'Koscica'),
('CROATIAN', 'Destilacija', 'Jedina muslimanska destilerija koja vec 150 godina proizvodi pivo i whiskey (u danasnjem Pakistanu)...', 'Murree'),
('CROATIAN', 'Dijalekt', 'Dubrovacki izraz za prozor', 'Funjestra'),
('CROATIAN', 'Diplomacija', 'Punomoc kojom neka osoba postaje zastupnik interesa domovine u stranoj drzavi?', 'Akreditacija'),
('CROATIAN', 'Dizajn', 'Ime bezvremenog stolca kojega je 1958. dizajnirao Arne Jacobsen.', 'Egg chair\nEgg'),
('CROATIAN', 'Drustvo', 'Marginalna grupa sa radikalno drukcijim shvacanjem svijeta i nacinom zivota razlicitim od norme koja postoji u ostatku drustva?', 'Kult\nSekta'),
('CROATIAN', 'Egipatska mitologija', 'Kako se zovu dva divovska kamena kipa sto prikazuju faraona Amenofisa III?', 'Memnonovi kolosi'),
('CROATIAN', 'Ekologija', '"Eko sustav nalikuje zidu iz kojega covjek polako...!"?', 'Izbija cigle'),
('CROATIAN', 'Ekonomija', '"Povoljne su sve promjene koje cine da je nekima bolje ako zbog njih nije nekome drugome losije" nacelo je...?', 'Ekonomije blagostanja'),
('CROATIAN', 'Elektronika', 'Cetvrti svjetski proizvodjac mobitela.', 'Sony Ericsson'),
('CROATIAN', 'Elektrotehnika', 'Abecednim redom navedite tri elektrode bipolarnog tranzistora?', 'baza emiter kolektor'),
('CROATIAN', 'Energija', 'Predsjednik ruskog naftnog giganta Gazproma.', 'Alexei Borisovich Miller'),
('CROATIAN', 'Engleski', 'Akronimi Engleskog jezika MSGS.?', 'messages'),
('CROATIAN', 'Engleski jezik', 'Caj', 'Tea'),
('CROATIAN', 'Enigmatika', 'Krizaljka s opisima u rubnim poljima?', 'Skandinavka'),
('CROATIAN', 'Enologija', 'Autohtona bijela sorta iz Hercegovine?', 'Zilavka'),
('CROATIAN', 'Etnologija', 'Sator sjevernoamerickih Indijanaca sa Srednjeg Zapada...', 'Tipi'),
('CROATIAN', 'Europa', 'Naziv za ozivljavanje i ujedinjenje Italije u 19. st..', 'Risorgimento'),
('CROATIAN', 'Europska Unija', 'Cetvrti kriterij za ulazak u EU, utemeljen u Madridu.', 'Administrativni kriterij'),
('CROATIAN', 'Ezoterija', 'Energetski centri ljudskog tijela.', 'Cakre'),
('CROATIAN', 'Farmacija', 'Ime lijeka protiv alergije na ambroziju...', 'Lectranal'),
('CROATIAN', 'Fig. izrazi', 'Biti neskroman, traziti vise nego sto trebas = Traziti...?', 'Kruha svrh pogace'),
('CROATIAN', 'Film', '"Andaluzijski pas" je nadrealisticki film L. Bunuela i...?', 'Salvadora Dalija'),
('CROATIAN', 'Film i TV', 'Autor crtanih filmova "Macak Fritz" i "Gospodar prstenova".', 'Ralph Bakshi'),
('CROATIAN', 'Film â€“James Dean', 'Â«Istocno od...Â»?', 'raja'),
('CROATIAN', 'Film/Glazba', 'Filmska glazba kao dio filmske trake ili na posebnom nosacu zvuka (engl.).', 'Soundtrack'),
('CROATIAN', 'Film/Knjizevnost', 'Am. pisac, glumac i scenarist (Chuck Yeager u "The Right Stuff").', 'Sam Shepard'),
('CROATIAN', 'Film/Strip', 'Majka lutalica ga je na svijet donijela u podrumu tal. restorana "Mamma Leone" sto je obiljezilo njegove prehrambene navike.', 'Garfield'),
('CROATIAN', 'Film/Televizija', 'Hrv. glumac, ostvario niz komicnih uloga ("Prosjaci i sinovi", "Velo misto")?', 'Spiro Guberina'),
('CROATIAN', 'Filmske veze', 'Svestrani filmas s kojim su podijelile dio zivota B. Bardot, J. Fonda i C. Deneuve.', 'Roger Vadim'),
('CROATIAN', 'Filmski biseri', 'Film Bretta Ratnera "Rush hour" kod nas je preveden:', 'Gas do daske'),
('CROATIAN', 'Filmski citati', 'Kathy Bates ("Diabolique"): "Testosteron. Njime bi trebalo..."?', 'Puniti bombe'),
('CROATIAN', 'Filozofija', '"Bitak" je?', 'Ono po cemu jest sve sto jest'),
('CROATIAN', 'Fizicari', 'Danski fizicar: otkrio elektromagnetizam.', 'Hans Christian Oersted'),
('CROATIAN', 'Fizika', '"Ako je neko tijelo "A" u toplinskoj ravnotezi s tijelom "B" i s tijelom "C", onda su tijela "B" i "C" u medjusobnoj toplinskoj ravnotezi." Koji je to zakon?', 'Nulti zakon termodinamike'),
('CROATIAN', 'Fizika/Filozofija', 'Teorija deterministickog kaosa ili teorija...?', 'Nelinearne dinamike'),
('CROATIAN', 'Fobije', 'Antofobija.?', 'Strah od cvijeca'),
('CROATIAN', 'Folklor', 'Chileanski kauboj...', 'Huaso'),
('CROATIAN', 'Formula', 'Staza utrke u Italiji.', 'Imola'),
('CROATIAN', 'Formula 1', 'Finski vozac koji je 1982. osvojio prvenstvo uz jednu jedinu pobjedu...', 'Keke Rosberg'),
('CROATIAN', 'Fotografija', 'Americka fotografkinja portreta (John i Yoko, etc.)...', 'Annie Leibovitz'),
('CROATIAN', 'Francuski', 'C''est la vie!', 'Takav je zivot'),
('CROATIAN', 'Francuski jezik', 'Evo, eto.', 'Voila'),
('CROATIAN', 'Gastornomija', 'Ovo ulje vrlo je slicno maslinovom po kvaliteti i okusu, pa u azijskoj kuhinji ima jednako vaznu ulogu kao maslinovo u mediteranskoj?', 'ulje kikirikija'),
('CROATIAN', 'Gastro', 'Poznati talijanski aperitiv jarko crvene boje?', 'campari soda\ncamparisoda'),
('CROATIAN', 'Gastronomija', '"Pice nase i vase mladosti".', 'Cocta'),
('CROATIAN', 'Generali', 'General-geodet, bjegunac...', 'Vladimir Zagorac'),
('CROATIAN', 'Genetika', 'Puni naziv za DNK - nuklensku kiselinu u obliku dvostruke, spirano zavijene zavojnice koja sadri geneticke odrednice za specificni bioloski razvoj stanicnih oblika zivota i vecine virusa.', 'Deoksiribonukleinska kiselina'),
('CROATIAN', 'Geografija', '"Old faithful" ime je najpoznatijeg svjetskog?', 'Gejzira'),
('CROATIAN', 'Geografije', '"Ukusni" otoci koji pripadaju Velikoj Britaniji.', 'Otoci Juzni Sandwich otoci\nSouth Sandwich Islands'),
('CROATIAN', 'Geologija', 'Americki seizmolog po kojem je nazvana skala za mjerenje jacine potresa.', 'Charles Richter'),
('CROATIAN', 'Geometrija', 'Mnogokut sa 3 stranice?', 'trokut'),
('CROATIAN', 'Germanizmi', 'Znanost.', 'Wissenschaft'),
('CROATIAN', 'Glazba', '"...... they''re all doing the monster mash and most of the taxis and the wores are only taking calls for cash" Naslov ove pjesme Dire Straits-a?', 'Your latest trick'),
('CROATIAN', 'Glazba i Film', 'Americki pjevac i filmski glumac...?', 'Frank Sinatra'),
('CROATIAN', 'Glazba/Arheologija', 'Zenski ostatci australopiteka otkriveni u Etiopiji 1974. i nazvani "Lucy", svoje ime duguju pjesmi grupe koju su arheolozi slusali na dan pronalaska. O kojoj je grupi rijec?', 'The Beatles '),
('CROATIAN', 'Glazba/Film', 'Hrv. sopranistica, dobitnica nagrade M. Trnina; ipak je najvise pamtimo kao glumicu u filmu "Tko pjeva zlo ne misli"?', 'Mirjana Bohanec'),
('CROATIAN', 'Gluopst', 'Koju vrstu obuce ima Kip Slobode?', 'sandale'),
('CROATIAN', 'Glupost', '"Idealne" mjere zene', '90 60 90'),
('CROATIAN', 'Gluposti', 'Cijev je sipka kroz koju je provucena...', 'Rupa'),
('CROATIAN', 'Gospodarstvo', 'Americka fransiza restorana brze prehrane dekorirana kao americke zalogajnice iz 1940-ih i 50-ih?', 'Johnny Rockets'),
('CROATIAN', 'Gospodrastvo', 'Malezija potice proizovdnju palminog ulja zbog povecane potraznje za?', 'bio-dizelom'),
('CROATIAN', 'Graditeljstvo', 'Omanja cigla.', 'Briket\nBriketa'),
('CROATIAN', 'Gradjevinarstvo', 'Kada se izgrade sve planirane autoceste u Hrvatskoj, biti ce ih ukupno.', '11\njedanaest'),
('CROATIAN', 'Gradjevine', 'Bivsi dvor ceskih kraljeva,sada rezidencija ceskog predsjednika i vlade?', 'Hradcany'),
('CROATIAN', 'Gradovi', 'Prva apoteka na Balkanu i druga u Europi?', 'Dubrovnik'),
('CROATIAN', 'Grafit', 'Dobre su djevojke dobre, ali lose....?', 'jos bolje'),
('CROATIAN', 'Grafiti', '"Bog je stvoria covika, a Zadar...', 'kosarku'),
('CROATIAN', 'Gramatika', '10 i 1 slovo abecede', 'f a'),
('CROATIAN', 'Grbovi', 'Krunu od pet siljaka na stitu sa sahovnicom zapravo cini pet...?', 'Povijesnih hrvatskih grbova'),
('CROATIAN', 'Grcka mitologija', 'Boginja (Bog) trenutne srece je ...', 'Kairos\nKaira'),
('CROATIAN', 'Grcki', 'Pcela?', 'melissa'),
('CROATIAN', 'Heraldika', 'Grb Licko-senjske zupanije na sebi ima zlatni cvijet ...', 'Degenije'),
('CROATIAN', 'Hobi', 'Sto skuplja filuminist?', 'kutije sibica'),
('CROATIAN', 'Hokej', 'Najjaci hrvatski hokejski klub', 'Medvescak'),
('CROATIAN', 'Homonimi', 'Baka u cakavskim krajevima, a nocna posuda u sjevernim.', 'Nona'),
('CROATIAN', 'Horoskop', 'Ako ste rodjeni na Novu Godinu, sto ste po horoskopu?', 'Jarac'),
('CROATIAN', 'Hrana', 'Autohtoni punomasni mekani hrvatski sir koji se proizvodi iz toplinski neobradjenog mlijeka.', 'Skripavac'),
('CROATIAN', 'Hrvatske tvrdjave', 'Dubrovacka?', 'Revelin'),
('CROATIAN', 'Hrvatski jezik', 'Posvojni pridjevi izvedeni od imena naseljena mjesta.', 'Ktetici'),
('CROATIAN', 'Hrvatski knezevi', 'Kronoloski ide Borna, Vladislav pa...?', 'Mislav'),
('CROATIAN', 'Humor', '"Cinjenica: Neki ljudi tvrdili su da je Chuck Norris izmisljotina. Vise nisu ..."?', 'Medju zivima'),
('CROATIAN', 'Igra', 'Najmanje vrijedna pikula.', 'obicnjaca'),
('CROATIAN', 'Igre', 'Igra bacanja plosnatog kamena koji bi trebao nekoliko puta odskociti na povrsini vode?', 'Zabica\nZabice'),
('CROATIAN', 'Imena', 'Ime Ana dolazi od hebr. imena Hannah sto znaci...?', 'milost'),
('CROATIAN', 'Industrija', 'Britanski Cornwall medjuostalome je poznat po vrijednim nalazistima...', 'kaolina'),
('CROATIAN', 'Informatika', '.koje godine je osnovana tvrtka Apple Computers?', '1975'),
('CROATIAN', 'Institucije', 'Institucija medjuregionalne suradnje na gotovo svim nepolitickom podrucjima (Hrvatska, Slovenija, Austrija...)?', 'Alpe-Jadran'),
('CROATIAN', 'Integracije', 'Program NATO-a za postupnu pripremu svojih buducih clanica.', 'Partnerstvo za mir'),
('CROATIAN', 'Internet', '"Very Easy Rodent Oriented Net-wide Index to Computerised Archives" - programski alat za trazenje datoteka na Internetu ili ukratko ...', 'Veronica'),
('CROATIAN', 'Istrazivanja', 'Cak 81 % muskaraca misli da su brinete prije svega...?', 'Inteligentne'),
('CROATIAN', 'Izbaci uljeza', 'Domino, jamb, monopoly, covjece ne ljuti se!', 'domino'),
('CROATIAN', 'Izdavastvo', 'Am. pandan nasem casopisu "Sam" ("Uradi sam").', 'Make'),
('CROATIAN', 'Izjave slavnih', 'Albert Einstein: Ako je A uspjeh u zivotu, onda je A = x plus y plus z. X je rad, Y je igra, Z je ...', 'Drzanje jezika za zubima'),
('CROATIAN', 'Izreke', '"Cuius regio, illius regio" u prenesenom znacenju danas znaci: Pokoravaj se zakonima...?', 'Zemlje u kojoj zivis'),
('CROATIAN', 'Izumi', 'BBB mogu biti zahvalni izumitelju dinama koji se zvao...', 'Michael Faraday'),
('CROATIAN', 'Jeste li znali', 'Svi polarni medvjedi su .........!', 'ljevoruki'),
('CROATIAN', 'Jezici', '"Badnjak" na spanjolskom jeziku.', 'Nochebuena'),
('CROATIAN', 'Jezik', '"Ilica" ("Ilidza") na turskom znaci ...', 'Izvor tople vode'),
('CROATIAN', 'Jezikoslovlje', 'Lingvist koji proucava jezicno znakovlje?', 'Semioticar'),
('CROATIAN', 'Kalendar', 'Koliko je 1976. godina imala dana?', '366'),
('CROATIAN', 'karikatura', 'Lik iz nekad svakodnevnih karikatura Ismeta Voljevice.', 'Grga Protokol'),
('CROATIAN', 'Kartografija', 'Linije koje na geografskim kartama spajaju mjesta jednakih srednjih godisnjih temperatura?', 'Hidroizoterme'),
('CROATIAN', 'Katastrofe', 'Indijski grad Bhopal 3.12.1984.g. iz tvornice pesticida ''Union Carbide'' poharan je istjecanjem 40t otrovnog plina...', 'Metil izocijanat'),
('CROATIAN', 'Kazaliste', 'Cvjetni prolaz u japanskim kazalistima koji spaja rubove pozornice s dnom gledalista?', 'Hanamichi'),
('CROATIAN', 'Kazaliste/Film', 'Mjuzikl "My fair lady" je nastao prema komediji G.B.Shawa ...', 'Pigmalion'),
('CROATIAN', 'Kemija', '"Alkoholnim vrenjem" nastaje alkohol poznat pod imenom?', 'etanol'),
('CROATIAN', 'Kinologija', 'Pasmina iz Romagne poznata po trazenju tartufa.', 'Lagotto Romagnolo'),
('CROATIAN', 'Kiparstvo', 'Hrvatski kipar (mauzolej Petra Petrovica Njegosa).', 'Ivan Mestrovic'),
('CROATIAN', 'Kjizevnost', 'Roman koji je Robert Louis Stevenson napisao pod utjecajem kokaina u sest dana i sest noci?', 'The Strange Case of Dr. Jekyll and Mr. Hyde'),
('CROATIAN', 'Kjnizevnost', 'Najstariji sacuvani ep na engleskom jeziku?', 'Beowulf'),
('CROATIAN', 'Knizevnost', 'Knjiga J.R.R. Tolkiena, slikovnica o nevoljama iz zivota Djeda Mraza.', 'The Father Christmas Letters\nPisma Djeda Mraza'),
('CROATIAN', 'Knjige', 'Ime dobrocudnog poludiva iz Harry Potter-a?', 'Hagrid'),
('CROATIAN', 'Knjiizevnost', 'Vrhunac Shakespeareovog opusa cetiri su velike tragedije: Hamlet, Otelo, Macbeth i ...?', 'Kralj Lear\nKing Lear'),
('CROATIAN', 'Knjizevnost', '"Ala je lep ovaj svet!" uzviknuo je baĹˇ on.', 'Jovan Jovanovic Zmaj'),
('CROATIAN', 'Knjizevnost / glazba', 'Epski pjevaci u staroj Grckoj?', 'Aedi i rapsodi'),
('CROATIAN', 'Knjizevnost/Film', 'Francuski "pjesnik Pariza" ("Barbara") i scenarist ("Obala u magli")?', 'Jacques Prevert'),
('CROATIAN', 'Knjizevnost/glazba', 'Dr. Faust je Mefistu prodao dusu da bi zauzvrat dobio...?', 'Bogatstvo i mladost'),
('CROATIAN', 'Knjizevnost/Politika', 'Senegalski pjesnik i politicar, predsjednik drzave 1960.-1980.?', 'Leopold Sedar Senghor'),
('CROATIAN', 'Knjizevost', 'Dovrsi stih Emily Dickinson "Bas onaj tko nije nikada iskusio odredjene osjecaje, vec je samo za njima ceznuo..."', 'Razumije ih u njihovoj punini'),
('CROATIAN', 'Knjizvenost', 'Groteskna pojava u komediji dell''arte, prozdrljiv i drzak lik, koji svakome kaze istinu u lice.', 'Pulcinella'),
('CROATIAN', 'Knjzevnost', 'Koje je pravo ime knjizevnika Ksavera Sandora Gjalskog?', 'Ljubomir Babic\nLjubo Babic'),
('CROATIAN', 'Kokteli', 'Koktel ciji su glavni sastojci rum, sok od ananasa i kokosovo mlijeko.', 'Pina colada'),
('CROATIAN', 'Komentatori', 'Milojko Pantic na derbiju Partizan - Crvena zvezda: "Evo izlaze igraci Partizana, a evo i..."?', 'nasih'),
('CROATIAN', 'Kratice', 'Anoniman autor - N.N.?', 'Nomen nescio'),
('CROATIAN', 'Kriminal', 'Flunitrazepam (tvornickog imena Rohypnol) nosi ulicno ime ...', 'Droga za silovanje'),
('CROATIAN', 'Kriminalistika', 'Osim otiska prstiju, jedinstven je i otisak ...', 'jezika'),
('CROATIAN', 'Kriminologija', 'U SAD-u se ubojstvo dogodi svake .. minute.', '23'),
('CROATIAN', 'Kuhanje', 'Tradicionalna istarska hrana od vina i kruha', 'Istarska supa'),
('CROATIAN', 'Kulinarstvo', 'Aromaticni plod tropskog drveta, stavlja se kao zacin u razna slatka i slana jela, morski orascic ili ...', 'Muskatni orascic'),
('CROATIAN', 'Kultura', '"Rugao se lonac loncu, a oba su...', 'crna'),
('CROATIAN', 'Kutura', 'Kako se zove prva zena primljena u Akademiju znanosti i umjetnosti?', 'Ivana Brlic Mazuranic'),
('CROATIAN', 'Kviz', 'biseri - Quizzard: Botanika - Uzgoj ruza.Tomi_G:', 'ruzarenje'),
('CROATIAN', 'Kviz biseri', 'Quizzard: Tehnologija - Riblje oko je sto?  _tantrum_:', 'kao macije'),
('CROATIAN', 'Kviz. biseri', 'Sjetva ili...? Master_Di: ...?', 'Kosidba'),
('CROATIAN', 'Kvizerski biseri', 'Administrativna teritorijalna jedinica u Francuskoj? pantagana: ...?', 'Depadansa'),
('CROATIAN', 'Latinizmi', 'Lupus in fabula?', 'vuk u prici'),
('CROATIAN', 'Latinska poslovica', 'Quot capita, tot sententiae.', 'Koliko glava, toliko misljenja'),
('CROATIAN', 'Latinske izreke', 'Ad calendas graecas.', 'Kad na vrbi rodi grozdje'),
('CROATIAN', 'Latinski', '"Ad Lib" je kratica za "Ad libitum" sto znaci ...?', 'Sa zadovoljstvom'),
('CROATIAN', 'Legende', 'Ceh je utemeljio Cesku, Leh Poljsku, a Meh...?', 'Rusiju'),
('CROATIAN', 'Lezik', 'Dva samoglasnika koja se izgovaraju zajedno, dvoglas ili...?', 'Diftong'),
('CROATIAN', 'Likovna umjetnost', '"Arnolfini i njegova zena" slika je koju je 1434.g. naslikao?', 'Jan van Eyck'),
('CROATIAN', 'Lingvistika', 'Blazi izraz koji se rabi umjesto nepristojnih, neugodnih, ruznih ili opasnih izraza?', 'Eufemizam'),
('CROATIAN', 'Lingvistikai', 'Lat. Indijska konoplja.', 'Cannabis sativa'),
('CROATIAN', 'Linux', 'Distribucija koja se koristi na Konzumovim blagajnama?', 'Red Hat'),
('CROATIAN', 'Ljepota matematike', '11111 x 11111 =', '123 454 321'),
('CROATIAN', 'Ljubavne veze', 'Frank Sinatra i prva dama koja nedostaje: Ava, Lauren, Mia, Rafaella, Juliet, Barbara i...?', 'Nancy'),
('CROATIAN', 'Ljuti protivnici', 'Ben Hur vs.?', 'Mesala'),
('CROATIAN', 'Logika', 'Kako se naziva istinosna funkcija koja je istinita kad je njen argument lazan, i lazna kad je njen argument istinit?', 'Negacija'),
('CROATIAN', 'Lov', 'Dozivanje zivotinja imitiranjem njihovog glasanja?', 'vabljenje'),
('CROATIAN', 'Ludi zakoni', 'Ako ste neudani u Floridi i zelite se provesti nedjeljom, to ne smije bit skakanje ...', 'Padobranom'),
('CROATIAN', 'Lutkarstvo', 'Lutka koja se pokrece pomocu konaca o kojima visi?', 'Marioneta'),
('CROATIAN', 'Manifestacije', 'Koncert odrzan 2007. na 7 kontinenata sa svrhom upozorenja na pogubne ekoloske promjene.', 'Live earth'),
('CROATIAN', 'Marketing', 'Zastitni znak poduzeca ili proizvoda, najcesce strogo definiran knjigom standarda...', 'Logo'),
('CROATIAN', 'Marketinski slogani', '"Apple Computer"', 'Think different'),
('CROATIAN', 'Matematika', '''-'' je znak oduzimanja; ''='' je znak jednakosti, a 3 crtice jedna ponad druge je znak ...', 'kongruencije'),
('CROATIAN', 'Medecina', 'Muska spolna zlijezda kroz koju prolazi mokracna cijev...?', 'Prostata'),
('CROATIAN', 'Medicina', '"Crna smrt".', 'Kuga'),
('CROATIAN', 'Medicini', 'Lijecnici specijalisti za ozljede.', 'Traumatolozi'),
('CROATIAN', 'Mediji', 'Cuvena komentatorica sportskih priredbi (umjetnicko klizanje, atletika), sada u mirovini.', 'Milka Babovic'),
('CROATIAN', 'Mehanika', 'Mehanicki zglob.', 'kardan'),
('CROATIAN', 'Meteorologija', 'Japanski meteorolog prema kojem je nazvana ljestvica za stupnjevanje tornada?', 'Tetsuyi Fujiti'),
('CROATIAN', 'Mikrobiologija', 'Cista mikrobna kultura ili?', 'monokultura'),
('CROATIAN', 'Militarizacija', 'Ruski energetski giganti kojima je Duma odobrila stvaranje vlastitih korporacijskih vojski...', 'Gazprom i Transneft'),
('CROATIAN', 'Minerali', 'Crveni dragulj, vrsta mineralnog korunda (aluminijevog oksida) u kojem crvena boja potjece od kroma?', 'Rubin'),
('CROATIAN', 'Mineralogija', 'Dragi kamen po tvrdoci odmah iza dijamanta.', 'Korund'),
('CROATIAN', 'Misli', 'Mark Eyskens:"EU je gospodarski div, vanjskopoliticki patuljak i crv na podrucju..?', 'Sigurnosne politike'),
('CROATIAN', 'Mitologija', 'Adonisova majka?', 'Mirha'),
('CROATIAN', 'Mitovi', 'Jazonov brod je prozvan Argo po njegovu...?', 'Graditelju'),
('CROATIAN', 'Mjere', 'Sto kilograma, kvintal ili..?', 'Metricka centa'),
('CROATIAN', 'Mobilna tehnologija', 'Znacenje kratice CLIP.', 'Caller Line Identification Presentation'),
('CROATIAN', 'Mobiteli', 'Dual-Band mobiteli rade na frekvencijama..', '900 1800'),
('CROATIAN', 'Moda', 'Americki modni casopis osnovan 1867. godine i danas jedan od najpoznatijih na svijetu?', 'Harper''s Bazaar'),
('CROATIAN', 'Monarhije', 'Posljednji apsolutisticki monarh Afrike, kralj Svazilanda...', 'Mswati III'),
('CROATIAN', 'Mostogradnja', 'Stubovi nosaci velikih razmjera...', 'Piloni'),
('CROATIAN', 'Motocikli', '"Nadimak" Hondinih naked modela CB-600F i CB-900F.', 'Hornet'),
('CROATIAN', 'Motociklizam', 'Hondin supersportski motocikl CBR-1000RR?', 'Fireblade'),
('CROATIAN', 'Mudre izreke', '"Kad si sretnan i sunce za tobom zuri".', 'Ivana Brlic Mazuranic'),
('CROATIAN', 'Mudrosti', '"Nista zemaljsko nije vrijedno velike zelje" - autor je ...', 'Arthur Schopenhauer'),
('CROATIAN', 'Murpheyevi zakoni', 'Svatko bi trebao vjerovati u nesto, ja vjerujem da cu ...', 'Popiti jos jedno pice'),
('CROATIAN', 'Murphyjevi zakoni', 'Ako ti se cini da je sve u redu...', 'Nesto ti je promaknulo'),
('CROATIAN', 'Muzika', '1988. godine Celine Dion je na Eurosongu zastupala koju zemlju?', 'svicarsku\nsvicarska'),
('CROATIAN', 'Nadopuni', '"Covjece pazi da ne ides malen ispod ..."?', 'zvijezda'),
('CROATIAN', 'Nakit', 'Dijamant brusen s mnogobrojnim facetama kojima se postize sjaj i rasprsenje bijele svjetlosti?', 'Briljant'),
('CROATIAN', 'Navodno', 'Ako ste tuzni i usamljeni, pomoci ce ako zidove obojite...?', 'Narancasto'),
('CROATIAN', 'Nazivi', 'Koji pisac je prvi uveo rijec ROBOT u upotrebu?', 'Karel Capek'),
('CROATIAN', 'NBA', 'Domicil Timberwolvesa.', 'Minnesota'),
('CROATIAN', 'Neurologija', 'Nepodnosljiva napetost koju bolesnik umanjuje ponavljanjem iste radnje, rijeci ili misli?', 'Kompulzivna opsesija'),
('CROATIAN', 'NHL Timovi', 'Anaheim?', 'Mighty Ducks'),
('CROATIAN', 'Njemacki', 'Avion.', 'Flugzeug'),
('CROATIAN', 'Njemacki jezik', 'Verboten!', 'Zabranjeno'),
('CROATIAN', 'Nogomet', 'Arthur Antunes Coimbra, desetka brazilske reprezentacije, nasljednik velikog Pelea, poznatiji kao...', 'Zico'),
('CROATIAN', 'Novac', 'Sto se nalazi na nalicju kovanice od 1 kune?', 'slavuj'),
('CROATIAN', 'Novinarstvo', '"Globusova" kolumnistica koja posprdno komentira dnevnopoliticke dogadjaje.', 'Tanja Torbarina'),
('CROATIAN', 'Nutricionizam', 'Jedno od povrca koje ima negativne kalorije?', 'celer'),
('CROATIAN', 'Obicaji', '"Dijete Isus" koje tradicionalno na Bozic donosi darove djeci u Njemackoji i Austriji.', 'Kristkind\nKristkindl'),
('CROATIAN', 'Obrazovanje', 'Obrazovni stupanj koji odgovara visoj skoli, VI. stupanj.', 'Bakalaureat'),
('CROATIAN', 'Obrt', 'Fini mrezasti rad od srebrne ili zlatne zice, slican cipki...', 'Filigran'),
('CROATIAN', 'Odgovori', 'Gdje?', 'ovdje\nondje\ntamo'),
('CROATIAN', 'Odlicja', 'Ciji lik nosi Red Danice hrvatske koji se dodjeljuje za osobite zasluge u gospodarstvu?', 'Blaza Lorkovica\nBlaz Lorkovic'),
('CROATIAN', 'Opca kultura', 'Kako glasi slogan Europske unije?', 'In varietate concordia\nUjedinjeni u raznolikosti'),
('CROATIAN', 'Opcenito', 'Kako nazivamo razliku izmedju stope radjanja i stope umiranja?', 'stopa prirodnog prirastaja'),
('CROATIAN', 'Organizacije', 'FAO je organizacija UN koja se brine za ...?', 'Poljoprivredu i prehranu'),
('CROATIAN', 'Oruzja', 'Bojna indijanska sjekira?', 'Tomahawk'),
('CROATIAN', 'Oruzje', '"Sluzbeni nadimak" americkog lovca F-16?', 'Fighting Falcon'),
('CROATIAN', 'Osobe', 'Poznati moderni slikar. Dizajnirao Alien-a', 'H.R. Giger'),
('CROATIAN', 'Otrov', 'Alkaloid iz sjemena stabla Strychnos Nux-Vomica poznat nam je pod nazivom ...', 'Strihnin'),
('CROATIAN', 'Oznake', '!', 'usklicnik'),
('CROATIAN', 'Palindromi', 'Da ili ne - A?', 'da'),
('CROATIAN', 'Parapsihologija', 'Izvanosjetilno prenosenje psihickih procesa jedne osobe drugoj.', 'Telepatija'),
('CROATIAN', 'Parovi', 'Romeo i ...', 'Julija\nJulia'),
('CROATIAN', 'Pismo', 'Dvoslovi hrvatske abecede?', 'dz lj nj'),
('CROATIAN', 'Pitalica', 'Imate kutiju s jednom sibicom i ulazite u hladnu i mracnu prostoriju u kojoj se nalaze svijeca, petrolejka i pec. Sto cete prvo upaliti?', 'Sibicu'),
('CROATIAN', 'Pitanje', 'Skandinavske zemlje imaju iste zastave samo razlicitih boja. DA ili NE?', 'DA'),
('CROATIAN', 'Pjesmica', 'Pisi, risi, ali znaj...?', 'listove mi ne trgaj'),
('CROATIAN', 'Ples', 'Egzotican folklorno-zabavni ples slican merengueu i brazilskoj sambi.', 'Tambor'),
('CROATIAN', 'Plovidba', 'Glavni uzduzni konstrukcijski element broda; proteze se od pramca do krme sredinom dna broda?', 'kobilica'),
('CROATIAN', 'Politicari', 'Bolivijski predsjednik...', 'Evo Morales'),
('CROATIAN', 'Politicki humor', 'Naziv za stranke u RH koje se registriraju netom prije izbora, s vrlo kratkim rokom "uporabe"?', 'Paloma stranke'),
('CROATIAN', 'Politika', '"Lijepa nasa" je postala sluzbenom himnom tadasnje SRH tek godine ...', '1972.\n1972'),
('CROATIAN', 'Politika i gospodarstvo', 'Robert Schuman i Jean Monnet su idejni zacetnici...?', 'Europske unije'),
('CROATIAN', 'Poljoprivreda', 'Rijeka na cijoj delti se u Europi uzgaja riza.', 'Rhone'),
('CROATIAN', 'Pomorstvo', 'Brik kojim je kapetan Ivan Visin iz Prcnja oplovio svijet?', 'Splendido'),
('CROATIAN', 'Porno', '80-ih i 90-ih vrlo popularna porno glumica.', 'Amber Lynn'),
('CROATIAN', 'Pornografija', 'Glavna glumica u kultnom pornicu ''Duboko Grlo''?', 'Linda Lovelace'),
('CROATIAN', 'Poslovica', 'Po jutru se ...?', 'Dan poznaje'),
('CROATIAN', 'Poslovice', '"Bleji u sarena vrata"?', 'Tele'),
('CROATIAN', 'Povijest', '"Izgubljeni grad" Inka?', 'Machu Picchu'),
('CROATIAN', 'Povijest EU', 'Koji prirodni resursi su najprije stavljeni pod zajednicku upravu?', 'Ugljen i celik'),
('CROATIAN', 'Povijest filma', 'Koje godine je George Eastman prvi put predstavio film u boji?', '1929'),
('CROATIAN', 'Povijest umjetnosti', 'Imitiranje gotike s kraja 19. i pocetka 20. st.?', 'Pseudogotika'),
('CROATIAN', 'Povijest/Knjizevnost', 'Putopis Alberta Fortisa iz 18. stoljeca u kojem opisuje nasu obalu.', 'Put po Dalmaciji'),
('CROATIAN', 'Povjest', 'Gdje je osnovan prvi partizanski odred?', 'Sisak'),
('CROATIAN', 'Povrce', 'Maslasta salata ili ...', 'Salata puterica'),
('CROATIAN', 'Poznate zadnje rijeci', 'Ne bi valjda udario cojeka sa .........?', 'naocalama'),
('CROATIAN', 'Poznati parovi', 'Ante Kostelic i?', 'Marica Kostelic'),
('CROATIAN', 'Pravo', '"Krajnjom nuzdom" se smatra ucinjeno zlo koje ne smije biti vece od onog koje je...?', 'Prijetilo'),
('CROATIAN', 'Pravopis', 'Bezvucni parnjak suglasniku d.', 'T'),
('CROATIAN', 'Predaja', 'Po narodnom vjerovanju ucenik koji zavrsi i 13., vrazju godinu skolovanja?', 'Grabancijas'),
('CROATIAN', 'Prehrana', 'Kako se nazivaju vegetarijanci koji izbjegavaju crveno meso, a konzumiraju piletinu i ribu?', 'Semivegetarijanci'),
('CROATIAN', 'Premetaljka', 'Kompjuterska terminologija "Crim"?', 'mIRC'),
('CROATIAN', 'Prevedite', 'najbolji(eng)', 'the best'),
('CROATIAN', 'Prijevod', 'Na engleskom naziv za lovackog psa?', 'hound'),
('CROATIAN', 'Prijevodi', 'Gaudeamus u prijevodu znaci ...?', 'Veselimo se'),
('CROATIAN', 'Priroda', '"Struk" biljke?', 'Vlat'),
('CROATIAN', 'Profesorski biseri', 'Profesor zemljopisa: Znajte, glavni grad mora biti glavni grad inace je ...', 'Sporedan'),
('CROATIAN', 'Programiranje', 'Ansi C funkcija za inicijalizaciju generatora slucajnog broja??', 'srand'),
('CROATIAN', 'Proizvodi', 'Po cemu je poznat grad Lepoglava?', 'po cipki'),
('CROATIAN', 'Promet', 'Brzina (km/h) koju je u srpnju 1976. postigao Lockheedov SR-71A?', '3529'),
('CROATIAN', 'Pseudonimi', 'Bird', 'Charlie Parker'),
('CROATIAN', 'Psihogija', 'Seksualna nastranost istovremene masturbacije i samogusenja, gdje je zadovoljstvo navodno povecano zbog povecane produkcije endorfina u stanju blizu gusenja?', 'Autoerotska asfiksijacija'),
('CROATIAN', 'Psihologija', '"Iskreni" osmijeh cije je obiljezje pomicanje kruznog ocnog misica?', 'Duchenneov osmijeh'),
('CROATIAN', 'Psiholohija', 'Najutjecajniji psiholog 20. stoljeca.', 'Burrhus Frederic Skinner\nSkinner'),
('CROATIAN', 'Ptice', 'Dugovrata ptica iz reda guscarica.', 'Labud'),
('CROATIAN', 'Publicistika', 'Naslov knjige u kojoj W.Engdahl iznosi teoriju zavjere po kojoj je GMO izmisljen radi smanjenja ljudske populacije.', 'Sjeme unistenja'),
('CROATIAN', 'Quiz biseri', 'Quizzard: Indijanski narod ciju drzavu unistava conquistador Cortes. ..nicola1:', 'hindu'),
('CROATIAN', 'Quizz biseri', 'Poslovice: riba ribi...? Tomi G:...', 'Sam u nju pada'),
('CROATIAN', 'Racunala', 'Godina formiranja Motorola kompanije (orginalno Galvin Manufacture Co)?', '1928'),
('CROATIAN', 'Racunalstvo', '"Warez" se odnosi na kakav software?', 'ilegalni'),
('CROATIAN', 'Racunari', 'Drugi naziv za knjigu "Common LISP: The Language"?', 'Aluminum book'),
('CROATIAN', 'Racunarsto', 'Tvrtka specijalizirana za proizvodnju sportskih simulacija (''NBA live'', ''Fifa'')', 'Electronic Arts'),
('CROATIAN', 'Racunarstvo', '"The X-Y Position Indicator For A Display System" ili koji hardverski prototip iz 1963.g.?', 'Mis'),
('CROATIAN', 'Radio', 'Koja radio drama je uzrokovala kaos u Americi?', 'Rat svjetova'),
('CROATIAN', 'Rano', 'Kako nazivaju Djeda Mraza u njegovoj domovini Laponiji?', 'Joulupukki'),
('CROATIAN', 'Rasa', 'Plava krv oznacava pripadnike koje klase?', 'plemstvo\nplemstva'),
('CROATIAN', 'Rat', 'Kamikaze se ne na neprijatelja obrusava avionom, tko juri u smrt torpedom?', 'kaiten'),
('CROATIAN', 'Ratovanje', 'Britanske padobranske postrojbe za posebne namjene?', 'Paras'),
('CROATIAN', 'Ratovi', 'Kako je nazvan sukob izmedju SAD i  SSSR poslije 1945. godine', 'Hladni rat'),
('CROATIAN', 'Razgovori', 'Obilaziti oko teme u razgovoru', 'okolisati'),
('CROATIAN', 'Raznno', 'Hrvatski botanicar iz Malog Losinja cija se bogata herbarska zbirka cuva u Botanickom zavodu PMF-a u Zagrebu.', 'Ambroz Haracic'),
('CROATIAN', 'Razno', '"7X" je predstavljao tajni sastojak kojeg pica?', 'Coca-Cole\nCoca-Cola'),
('CROATIAN', 'Registracije', 'Registarska oznaka Belog Manastira', 'Bm'),
('CROATIAN', 'Reklame', '...Bilo kuda kiki..."?', 'Svuda'),
('CROATIAN', 'Rekorderi', 'Svjetski rekorder u voznji automobilom, poginuo u "plavoj ptici" pri brzini od 960km/h?', 'Donald Campbell'),
('CROATIAN', 'Rekordi', 'Kako se zvalo plovilo kojim je 20.11.1977. postavljen trenutno vazeci svjetski brzinski rekord na vodi?', 'Spirit Of Australia'),
('CROATIAN', 'Rekreacija', 'Muski rekord u penjanju do vrha stubista Empire State Buildinga iznosi...', '573 sekunde'),
('CROATIAN', 'Religija', '"Cisterciti strozeg obreda" poznatiji su nam po imenu ...', 'Trapisti'),
('CROATIAN', 'Religije', 'Skola Mahayana budizma na Dalekom istoku?', 'Zen'),
('CROATIAN', 'Ribarstvo', 'Mreza potegaca za lov gira?', 'Migavica'),
('CROATIAN', 'Rijeci', 'Arhaicni regionalizam za rijec zgrabiti (Ljubo Cesic Rojs)...?', 'Jamiti'),
('CROATIAN', 'Rimski brojevi', '1268?', 'mcclxviii'),
('CROATIAN', 'Robotika', 'Covjekoliki robot.', 'Android'),
('CROATIAN', 'Rudarstvo', 'Rudarska ili ... svjetiljka.', 'Davyjeva'),
('CROATIAN', 'Ruski', 'Istina?', 'pravda'),
('CROATIAN', 'Sah', 'Cetvrti sahovski svjetski prvak, doktor prava i ruski aristokrat.', 'Aleksandar Aljehin\nAleksandar Aleksandrovic Aljehin'),
('CROATIAN', 'Sala', 'Boji se macaka :)?', 'Mis'),
('CROATIAN', 'San svakog muskarca', 'Netaknuta djevica (lat.).', 'Virgo intacta'),
('CROATIAN', 'Satelitska terminologija', 'Brzina digitalnog prijenosa, obicno se izrazava u Mb/s.', 'Bit rate'),
('CROATIAN', 'Scena', 'Ministar vanjskih poslova "Republike Pescenice".', 'Seva'),
('CROATIAN', 'Seksizam', 'Pametniji i jaci spol.', 'Muski'),
('CROATIAN', 'Seksologija', 'Kulminacijska tocka spolnog odnosa.', 'Orgazam'),
('CROATIAN', 'Serija', 'Star Trek: Zemlja podrijetla Williama Rikera.', 'Aljaska'),
('CROATIAN', 'Serije', 'Americka glumica poznata po ulozi Betty Suarez u americkoj sapunici ''Ugly Betty''.', 'America Ferrera\nAmerica Georgine Ferrera'),
('CROATIAN', 'SF', 'Ime klase kojoj pripada Enterprise-B?', 'excelsior'),
('CROATIAN', 'Simboli', 'Koju drzavu simbolizira tulipan?', 'Nizozemsku\nNizozemska'),
('CROATIAN', 'Sinomimi', 'Les.', 'Kadaver'),
('CROATIAN', 'Sinonim', 'Nadzornik.', 'Supervizor'),
('CROATIAN', 'Sinonimi', '"Kljuc za Indiju"', 'Sueski kanal'),
('CROATIAN', 'Skolstvo', 'Prostorija za skolsku nastavu', 'Ucionica'),
('CROATIAN', 'Skracenice', '"Drzavni zavod za proizvodnju lijekova i vakcina" nama je poznatiji kao...?', 'Pliva'),
('CROATIAN', 'Slang', 'Popricati s nekim?', 'baciti spiku\nbaciti sprehu'),
('CROATIAN', 'Slastice', 'Punjeni cokoladni bomboni', 'praline'),
('CROATIAN', 'Slavenska mitologija', 'Legendarni Istocnoslavenski zli kucni duh koji se pojavljuje u liku malene zene koja brine o domacim zivotinjama, a neprijateljski je raspolozena prema muskarcima, te nocu uznemirava djecu.', 'Kikimora'),
('CROATIAN', 'Slavni', 'Frank Sinatra je bio slavni americki?', 'pjevac'),
('CROATIAN', 'Slavni parovi', 'Glumica i monarh.', 'Grace Kelly i Reinier III'),
('CROATIAN', 'Slicnosti', 'Kineska igra slicna dominu.', 'Mahjong'),
('CROATIAN', 'Slikari', 'Najslavniji katalonski slikar.', 'Salvador Dali'),
('CROATIAN', 'Slikarstvo', 'Austrijski slikar, predstavnik ekspresionizma', 'Oskar Kokoschka'),
('CROATIAN', 'Slogani', 'Nadopunite: "Bacite peglu kupite ..."?', 'tico'),
('CROATIAN', 'Smijesane rijeci', 'cixeom?', 'Mexico'),
('CROATIAN', 'Smisao Zivota', 'Zasto igramo ovaj kviz?', 'jer nam je dosadno\njer nam je dosadno'),
('CROATIAN', 'Smjesane rijeci', 'Broj "Rit"?', 'tri'),
('CROATIAN', 'Smjesne stvari', 'Dobitnica ovogodisnje nagrade Ine u iznosu od 50 000 kuna za promicanje hrvatske kulture u svijetu.', 'Mirjana Sanader'),
('CROATIAN', 'Sociologija', 'Autoritarizam se razlikuje od totalitarizma zbog svoje manje ideoloske...', 'indoktriniranosti'),
('CROATIAN', 'Software', 'Najbolji i najpopularniji software za obradu slike?', 'Photoshop'),
('CROATIAN', 'Speleologija', 'Najdublja jama u Hrvatskoj (1392 m)?', 'Lukina jama'),
('CROATIAN', 'Sport', '"Bozja ruka".', 'Diego Maradona'),
('CROATIAN', 'Sport MLB', 'Nadopunite Anaheim ...?', 'Angels'),
('CROATIAN', 'Sport NFL', 'Nadopunite Arizona ...?', 'Cardinals'),
('CROATIAN', 'Sport NHL', 'Anaheim ...', 'Ducks'),
('CROATIAN', 'Stadioni', 'Stadion na kojem igra Bologna', 'Dall''Ara'),
('CROATIAN', 'Stanovnistvo', 'Anticki stanovnici Skotske.', 'Pikti'),
('CROATIAN', 'Star Trek', 'Glumac koji je glumio Dr. McCoya', 'DeForrest Kelley'),
('CROATIAN', 'Star Wars', 'Glumio Obi-Wan Kenobija u "Phantom Menace"', 'Ewan McGregor'),
('CROATIAN', 'Stari zanati', 'Onaj koji krpa stare lonce obilazeci kucanstva?', 'Kotlokrpa'),
('CROATIAN', 'Stihovi', 'Dovrsi: "Oprosti mi ..."', 'pape'),
('CROATIAN', 'Strahovi', 'Androfobia je strah od?', 'muskaraca'),
('CROATIAN', 'Strane rijeci', 'Holizam dolazi od grcke rijeci holos sto znaci?', 'cijel\npotpun'),
('CROATIAN', 'Strani jezici', 'Ako se u Italiji zovete Alba, u Hrvatskoj cete biti?', 'Zora'),
('CROATIAN', 'Stranke', 'Socijaldemokratska stranka Velike Britanije.', 'Laburisticka stranka'),
('CROATIAN', 'Strategije', 'Munjeviti rat.', 'Blitzkrieg'),
('CROATIAN', 'Strip', '"Tko vrijedi, leti, tko leti, vrijedi, tko ne leti,...', 'ne vrijedi'),
('CROATIAN', 'Stripovi', 'Autor Strumpfova.', 'Peyo'),
('CROATIAN', 'Strojarstvo', 'Energetski stroj za pretvaranje kineticke energije strujanja u mehanicki rad?', 'Turbina'),
('CROATIAN', 'Studenti', 'Student pred zavrsetkom studija.', 'Apsolvent'),
('CROATIAN', 'Sumarstvo', 'Izuzetno kvalitetno drvo indijskog hrasta.', 'Tikovina'),
('CROATIAN', 'Svemir', 'Erupcija velike mase plinova na povrsini Sunca.', 'Protuberanca'),
('CROATIAN', 'Talijanski', 'Bez.', 'Senza'),
('CROATIAN', 'Talijanski jezik', 'Cvor, uzao.', 'Grop'),
('CROATIAN', 'Teatar', 'Popularno kazaliste u epohi Fadila Hadjica.', 'Jazavac'),
('CROATIAN', 'Tehnicki', 'Izumio (usavrsio) parni stroj?', 'James Watt'),
('CROATIAN', 'Tehnika', 'Hidroplan umjesto stajnog trapa ima...?', 'Plovni trap'),
('CROATIAN', 'Tehnologija', 'Aleksandrijski izumitelj prve naprave pokretane parom.', 'Heron'),
('CROATIAN', 'Telefonija', 'Pozivni broj Turkmenistana?', '993'),
('CROATIAN', 'Televizija', 'ALFov mracni predmet zelja, macak...?', 'Srecko\nLucky'),
('CROATIAN', 'Televizijski citati', '"Will i Grace":" Jezik je nastao kad su se rodili ruzni ljudi koje je trebalo..."?', 'Ogovarati'),
('CROATIAN', 'Tenis', 'Argentinski tenisac armenskog podrijetla.', 'David Nalbandian'),
('CROATIAN', 'Terorizam', '9/1 2004. je za Ruse u Sjevernoj Osetiji spomen na gotovo 400 poginulih (vecinom djece), u cecenskoj opsadi i kaoticnom oslobadjanju zatocenih osnovnoskolaca u gradu...', 'Beslanu'),
('CROATIAN', 'Test brzine', '"6345532412" napisati obrnuto', '2142355436'),
('CROATIAN', 'Tiskarstvo', 'Prvi otisak, primjerak prvog izdanja (ili: prvotni rukopis)?', 'Arhetip'),
('CROATIAN', 'Titule', 'Biskup ili nadbiskup koji nije uzdignut do ranga kardinala?', 'Monsinjor'),
('CROATIAN', 'Tolkien', '"Bijeli grad", prijestolnica Gondora?', 'Minas Tirith'),
('CROATIAN', 'Topcoder', 'Koliki najmanje mora biti rating za crvenu boju?', '2200'),
('CROATIAN', 'Tradicija', 'Staro dalmatinsko jelo Poljicke republike, sastojci: razvuceno tijesto, blitva, kapula i premaz od ulja s cesnjakom.', 'Soparnik'),
('CROATIAN', 'Transport', 'Buducnost transporta: kombinacija leteceg tanjura i amfibije, konstrukcija aeronautickog inzenjera Paula Mollera...', 'M200G Volantor'),
('CROATIAN', 'Trgovina', 'Cin kojim se obavlja nagodba; trgovacki ugovor?', 'Transakcija'),
('CROATIAN', 'Turcizam', 'Dilber.', 'Ljubavnik'),
('CROATIAN', 'Turcizmi', 'Kredit, povjerenje.', 'Veresija'),
('CROATIAN', 'Turizam', 'Izmedju koja dva grada se vozi "Maraton ladja"?', 'Metkovic i Ploce\nMetkovica i Ploca'),
('CROATIAN', 'TV', 'Americka znanstveno - fantasticna serija, karakteristicna po tome sto je i prije samog pocetka snimananja imala zacrtanu cijelu pricu.', 'Babylon 5'),
('CROATIAN', 'TV serije', 'Lik iz "Mucki" karakteristican po svojoj bradi i "lovackim pricama"?', 'Ujak Albert'),
('CROATIAN', 'Ucenicki biseri', 'Grcki novac se zove ...', 'Drakula'),
('CROATIAN', 'Umijetnost', 'U kojem je slavnom pariskom kabareu Lautrec bio cest gost?', 'Moulin rouge'),
('CROATIAN', 'Umjetnici', 'Biokemicar i pisac sf romana, porijeklom zidov, rodjen u rusiji?', 'isaac asimov'),
('CROATIAN', 'Umjetnost', '"Doruckom na travi" i "Olimpijom" sokirao je cijeli Pariz.', 'Edouard Manet'),
('CROATIAN', 'Umjetnost/Religija', 'Svetac kojega u likovnim umjetnostima prikazuju probodenog strjelicama?', 'Sebastijan'),
('CROATIAN', 'Urbanizam', 'Broj gradskih cetvrti Zagreba...', '17\nsedamnaest'),
('CROATIAN', 'Uredjaji', 'Sto mjeri kronometar', 'vrijeme'),
('CROATIAN', 'Ustanove', 'Amer. ustanova osnovana s namjerom posmrtnog odavanja pocasti zasluznim Amerikancima.', 'Hall of fame\nDvorana slave'),
('CROATIAN', 'Utjecaj reklama', '"MIlka": Samo ljubicaste krave su...?', 'Zdrave krave'),
('CROATIAN', 'Uzrecice', 'Avercenko:Sretni ljudi ne gledaju na...?', 'sat'),
('CROATIAN', 'V.I.P.', 'Betty Davis je jednom rekla za Joan Crawford: "Ona je spavala sa svim muskim glumcima iz MGM-a, osim sa......."?', 'lassie'),
('CROATIAN', 'Valute', 'Novac u Danskoj', 'Kruna'),
('CROATIAN', 'Veselice', 'Kartaska igra sa 2 snopa po 52 karte i 2 jokera.', 'Remi\nRummy'),
('CROATIAN', 'Vic', 'Gospodine, kada ste shvatili da ste krava ? - Davno, davno...kad sam jos bio... ?', 'tele'),
('CROATIAN', 'Vicevi', 'Idu dve cackalice ulicom i sretnu lizalicu. Kaze jedna onoj drugoj: ...', 'vidi onog glavonje'),
('CROATIAN', 'Vina', 'Jedna od najpoznatijih sorti grozdja, francuskog podrijetla?', 'Cabernet Sauvignon'),
('CROATIAN', 'Vjerovanja', 'Obicaj stvaranja buke u novogodisnjoj noci vuce korijene iz vjerovanja da se tako ...?', 'Tjeraju demoni'),
('CROATIAN', 'Vjetrovi', 'topao i suh vjetar u alpama', 'fen'),
('CROATIAN', 'Voce', 'Azijska kruska ili ...', 'Nashi'),
('CROATIAN', 'Vojska', 'Baloni vezani celicnom uzadi iznad gradova kojima se ometalo bombardiranje u 2. svj. ratu?', 'Barazni baloni'),
('CROATIAN', 'Vozila', 'Amfibijsko vozilo s trupom nalik na camac, pogonjeno avionskim propelerom, koje se najvise koristi u mocvarama?', 'Hidrokopter'),
('CROATIAN', 'Vrazje stvari', 'Neprijateljska sila kojom upravlja Sotona.?', 'Magog'),
('CROATIAN', 'Vrijeme', 'Dan poslije tekuceg dana.', 'Sutra'),
('CROATIAN', 'Vrsta poligamije', 'bracna veza muskarca s vise zena.', 'Poliginija'),
('CROATIAN', 'Vrste', 'Ribe preci kopnenih kraljeznjaka.', 'Resoperke'),
('CROATIAN', 'XXX', 'Stil bicevanja u sadomazohizmu kod kojeg dva bicevaoca naizmjence ritmicki i po odredjenom obrascu bicuju zrtvu?', 'firentinsko bicevanje'),
('CROATIAN', 'Za inteligentne', 'koliko je 10 i 30?', 'pola jedanaest'),
('CROATIAN', 'Zabava', 'Amatersko pjevanje na javnom mjestu uz snimljenu glazbu?', 'Karaoke'),
('CROATIAN', 'Zafrkancija', 'Kratica ofr.?', 'obicni fizicki radnik'),
('CROATIAN', 'Zagonetka', '5 golubova na grani. Dodje lovac i pogodi jednog puskom. Koliko je golubova ostalo na grani?', '0\nnijedan'),
('CROATIAN', 'Zagonetke', 'Crven jarac po pecini skace.', 'Jezik'),
('CROATIAN', 'Zagreb', 'Sumovita pjesacka staza koja spaja Tuskanac i Cmrok.', 'Dubravkin put'),
('CROATIAN', 'Zajednice', 'Brak.', 'Matrimonij'),
('CROATIAN', 'Zakon', 'Pismeno podnijeta optuzba', 'optuznica'),
('CROATIAN', 'Zakoni', 'Koja drzava SADa je predlozila zakon da broj Pi iznosi 3?', 'indiana'),
('CROATIAN', 'Zamljopis', 'Poznato skijaliste u Italiji?', 'Santa Caterina'),
('CROATIAN', 'Zanimljivo', 'Po njemu, spoznaja je moguca samo ako se oslobodimo ukorijenjenih predrasuda i laznih pojmova (idola). On je jedan od osnivaca modernog materijalizma?', 'Francis Bacon'),
('CROATIAN', 'Zanimljivost', '"Everyman" (engleska alegorijska igra iz 15.st.) kod nas se prevela kao...?', 'Svatkovic'),
('CROATIAN', 'Zanimljivosti', '"Guinnessova knjiga rekorda" drzi rekord kao ...', 'Najcesce ukradena knjiga iz knjizara'),
('CROATIAN', 'Zdravlje', 'Izlucevina zdrijelnih zlijezda pcela radilica, koristi se za poboljsanje imuniteta?', 'maticna mlijec'),
('CROATIAN', 'Zemljopis', '"Biser" sjevernog Jadrana?', 'Opatija'),
('CROATIAN', 'Zemljopis i nogomet', 'Povijesna pokrajina u jugozapadnoj Francuskoj i prezime poznatog engleskog nogometasa', 'Gascoigne'),
('CROATIAN', 'Zemljopis/fizika', 'Vjetar od 12 bofora i jacine 118-133km/h.', 'Orkan'),
('CROATIAN', 'Zene izumitelji', '1950.g. Marion Donovan izumila je nepromocive ...', 'Jednokratne pelene'),
('CROATIAN', 'Zgrade', 'Koje godine je dovrsen Empire State Building?', '1931'),
('CROATIAN', 'Ziva istina', 'Sa godinama koji se organ brze smanjuje u muskraca nego u zena?', 'Mozak'),
('CROATIAN', 'Zivotinja', 'Autohtona vrsta macke porijeklom iz Sibira, zelenih ociju i kratke, mekane dlake sa srebrnasto plavim odsjajem.', 'Ruska plava macka\nRussian Blue cat'),
('CROATIAN', 'Zivotinje', '"Lastin rep" ili "Admiral"?', 'Leptir'),
('CROATIAN', 'Znacenja', 'Sto znaci rijec kamikaza?', 'Poslanici bozjeg vjetra'),
('CROATIAN', 'Znanost', '1940 godine pocela je proizvodnja antibiotika u motrenim uvijetima pomocu cega?', 'mikroorganizama'),
('CROATIAN', 'Znanost/knjizevnost', 'Perzijski matematicar i pjesnik ("Rubaije")?', 'Omar Hajjam'),
('CROATIAN', 'Znanosti', 'Ihtiologija proucava sto...?', 'ribe'),
('CROATIAN', 'Znanstvenici', 'Englez, otkrivac Havajskog otocja i Australije koji je dokazao da je Antarktik okruzen Oceanom?', 'James Cook'),
('CROATIAN', 'Zodijak', 'Jedini znak koji ne predstavlja zivo bice je ...?', 'vaga'),
('CROATIAN', 'Zoologija', '"Papucari" morskog svijeta (zenke snesu jaja u njihove trbusne vrecice, a oni nose trudnocu i radjaju zive mlade).', 'Silo i morski konjic'),
('CROATIAN', 'Zrakoplovstvo', 'Americki lovac dugoga dometa i jedan od najuspjesnijih tipova za borbu 1-na-1 u II. sv. ratu.', 'P-51 Mustang'),
('ENGLISH', '-isms', 'a diseased condition resulting from the use of beverages such as whiskey.', 'alcoholism'),
('ENGLISH', '007', 'how does bond introduce himself on meeting someone for the first time', 'my name is bond, james bond'),
('ENGLISH', '11', '37 pm in military time is how many hours', '2337'),
('ENGLISH', '1960''s', 'who recorded "groovin''"?', 'young rascals'),
('ENGLISH', '1961 movies', 'name one of the major stars in "the errand boy"', 'jerry lewis'),
('ENGLISH', '1964', 'He was appointed Deputy Commander of Military Assistance', 'westmoreland'),
('ENGLISH', '1980s GrabBag', 'C. American strongman who appeared on a Time cover entitled "The Drug Thugs"', 'general manuel noriega'),
('ENGLISH', '1984 movies', 'name one of the major stars in "silence of the heart"?', 'mariette hartley'),
('ENGLISH', '1985 movies', 'name one of the major stars in "sins of the fathers"?', 'julie christie'),
('ENGLISH', '1990', 'what is the #5 us daily newspaper with 1,117,376 average circulation', 'new york times'),
('ENGLISH', '1991 gulf war', 'what missiles did the allies use to intercept iraqi scuds', 'patriots'),
('ENGLISH', '1992', 'What Biblical disease did 39 Texans come down with in 1992', 'leprosy'),
('ENGLISH', '1992 Movies', 'Name one of the major stars in "Diggstown"', 'james woods'),
('ENGLISH', '1993', 'name one of the major stars in the film cliffhanger', 'john lithgow'),
('ENGLISH', '1993 Movies', 'Name one of the major stars of "Indecent Proposal"', 'woody harrelson\ndemi moore'),
('ENGLISH', '1993 The Year', '$20 billion of financial aid went to this nation.', 'russia'),
('ENGLISH', '1997 Great Events', 'Stock markets on this continent plunged in October.', 'asia'),
('ENGLISH', '19th Cent Art', '"Death of Marat" and "Oath of the Horatii", two of his better known works', 'jacques-louis david'),
('ENGLISH', '5', '45 pm in military time is how many hours', '1745'),
('ENGLISH', '50s', 'Born in 1959, she was the actress possessed by the Devil in The Exorcist.', 'blair'),
('ENGLISH', '50s Authors', 'A Death in the FamilyXX: A Death in the Family', 'james agee'),
('ENGLISH', '60"s tv', 'what was "gentle ben"?', 'bear'),
('ENGLISH', '60''s tv', 'what bank did the "beverly hillbillies" swear by?', 'commerce bank'),
('ENGLISH', '60s', '1964 release was the most successful Disney film to date.', 'mary poppins'),
('ENGLISH', '60s Authors', 'Goodbye, Columbus', 'phillip roth'),
('ENGLISH', '7', '25 pm in military time is how many hours', '1925'),
('ENGLISH', '70''s Name the Artist', '(don''t fear) the reaper', 'blue oyster cult'),
('ENGLISH', '70s', 'Angola won its independence fromthem in 1975.', 'portugal'),
('ENGLISH', '70s Authors', 'A Book of Common Prayer', 'joan didion'),
('ENGLISH', '80''s Films', 'a dirty mind is a terrible thing to waste', 'steel magnolias'),
('ENGLISH', '80''s Name the Artist', 'he''ll never love you (like i do)', 'freddie jackson'),
('ENGLISH', '80s', 'G.D. Searle & Co put this brand sweetener on the market in 1983.', 'nutrasweet'),
('ENGLISH', '80s Films', '"In the Southeast, they say if you want to go to heaven, you have to change planes in Atlanta."', 'Accidental Tourist'),
('ENGLISH', '90''s Name the Artist', '3 a.m. eternal', 'the klf');
