pom:
  groupId: $groupId$
  artifactId: $artifactId$
  version: $version$
  name: $name$

# Logging configuration
logging:
  path: logs
  file: $artifactId$

# Database configuration
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql:///quiz?autoReconnect=true&useUnicode=true
    username: quizbot
    password: quizbot
    # http://www.codingpedia.org/ama/tomcat-jdbc-connection-pool-configuration-for-production-and-development/
    initialSize: 5
    maxActive: 55
    maxIdle: 21
    minIdle: 13
    timeBetweenEvictionRunMillis: 34000
    minEvictableIdleTimeMillis: 55000
    validationQuery: SELECT 1
    validationInterval: 34000
    testOnBorrow: true
    removeAbandoned: true
    removeAbandonedTimeout: 55
    initialize: false
    data: data.sql

spring.jpa.hibernate.ddl-auto: update


# ----------------------------------------------------------
# IRC configuration
# ----------------------------------------------------------

irc:
  startIdent: false
  servers:
  - hostname: irc.fpz.hr
    port: 6667
    autoNickChange: true
    encoding: WINDOWS-1250
    name: Spark
    nickServPassword: null
    login: spark 
    realName: $artifactId$ by ztomic, v$version$
    maxLineLength: 380
    messageLimit: 15
    messageLimitInterval: 2
    quiz: true
    channels:
    - name: #quiz
      language: CROATIAN
      quiz: true
    - name: #quiz-en
      language: ENGLISH
      quiz: true
  - hostname: callidus.sytes.net
    port: 6667
    autoNickChange: true
    encoding: WINDOWS-1250
    name: Spark
    nickServPassword: null
    login: callidus
    realName: $artifactId$ by ztomic, v$version$
    maxLineLength: 800
    messageLimit: 30
    messageLimitInterval: 1
    quiz: true
    channels:
    - name: #quiz
      language: CROATIAN
      quiz: true
    - name: #quiz-en
      language: ENGLISH
      quiz: true