INSERT INTO `questions` (`language`, `theme`, `question`, `answers`) VALUES
('CROATIAN', 'Aeronautika', 'Kojom brzinom najcesce lebde jedrilice?', '70 km/h'),
('CROATIAN', 'Aforizmi', 'Cuvajte drvece - na njima su zivjeli...?', 'nasi preci'),
('CROATIAN', 'Agronomija', 'Uzgoj svinja.', 'Svinjogojstvo'),
('CROATIAN', 'Akronim', 'HINA.', 'Hrvatska izvjestajna novinska agencija'),
('CROATIAN', 'Akronimi', 'Akronim Medjunarodnog skijaskog saveza.', 'FIS'),
('CROATIAN', 'Aktualno', 'Britanska djevojcica nestala polovicom 2007. u Portugalu, za sto policija naposlijetku okrivljuje njene roditelje?', 'Madeleine McCann'),
('CROATIAN', 'Alpinizam', 'Najtezi vrh u Alpama (4478 m)?', 'Matterhorn\nMonte Cervino'),
('CROATIAN', 'Anagram', 'Dogadaj: "Puno se kaki o mrtvim"?', 'komemorativni skup'),
('CROATIAN', 'Anagrami', '"L O V A K O"', 'Olovka'),
('CROATIAN', 'Anatomija', 'Abdominalna zlijezda u kojoj se razaraju stari eritrociti, te koja sluzi kao rezervoar krvi?', 'slezena'),
('CROATIAN', 'Anegdota', 'Jedan Parizanin se svaki dan uspinjao na Eiffelov toranj jer je to bilo jedino mjesto gdje mu nije stalno...?', 'Bio pred ocima'),
('CROATIAN', 'Anglizmi', 'Drustvene znanosti.', 'Humanities'),
('CROATIAN', 'Animacije', 'Crtani film o maloj vili, cehoslovacke proizvodnje?', 'vila amalka'),
('CROATIAN', 'Animirani film', '"Heraklo" - Heraklov ucitelj?', 'phil\nphiloctetes'),
('CROATIAN', 'Anomalije', 'Pojava vise od 5 prstiju na udovima.', 'polidaktilija'),
('CROATIAN', 'Antonimi', 'Akcija', 'Reakcija'),
('CROATIAN', 'Antropologija', 'Utemeljitelj strukturalizma u antropologiji?', 'Claude Levi-Strauss'),
('CROATIAN', 'Arheologija', 'Broncani anticki kip, izronjen iz losinjskog akvatorija 27.04.1999.g., koji predstavlja grckog atletu u prirodnoj velicini koji poslije utrke struze sol sa svoga tijela, rad Lizipa iz 4.st.pne.', 'Apoksiomen'),
('CROATIAN', 'Arhitektura', '1997. g. u Bilbau je otvorena jedna od najljepsih zgrada na svijetu?', 'Muzej Guggenheim\nGuggenheim Museo\nGuggenheim muzej'),
('CROATIAN', 'Arihetktura', 'Zdarski aritekt svjetskog glasa poznat u nas po Morskim Orguljama i Pozdravu suncu...?', 'Nikola Basic'),
('CROATIAN', 'Arihtektura', 'Sibensku katedralu gradili su Juraj Dalmatinac i ...', 'Nikola Firentinac'),
('CROATIAN', 'Aritektura', 'Najpoznatiji spomenik Maorske aritekture i umjetnosti u Spanjolskoj, dvorac kraj Granade.', 'Alhambra'),
('CROATIAN', 'ASCII kodovi', 'Znak '' ''?', '32'),
('CROATIAN', 'Asocijacija', 'Frigidarij, tepidarij, kaldarij, lakonij.', 'Rimska kupelj'),
('CROATIAN', 'Asocijacije', 'Auto, mesar, kapetan, motika.', 'Kuka'),
('CROATIAN', 'Astrofizika', 'Hipotetska tvorevina u prostorvremenu koja bi mogla posluziti kao precac kroz prostor i vrijeme?', 'crvotocina'),
('CROATIAN', 'Astrologija', 'Ako ste rodjeni 3.5. (jurkijev datum) koji ste horoskopski znak?', 'Bik'),
('CROATIAN', 'Astronautika', 'Americki naziv za Sputnik I?', 'Explorer I'),
('CROATIAN', 'Astronomija', '"Crvena planeta" je drugi naziv za koji planet..?', 'Mars'),
('CROATIAN', 'Atletika', 'Hrvatski rekorder u desetoboju...', 'Josko Vlasic'),
('CROATIAN', 'Auto moto', 'Automobil koji se prodavao s reklamnim sloganom "malo trosi , puno daje"...?', 'Yugo'),
('CROATIAN', 'Automobili', '....... Espace?', 'Renault'),
('CROATIAN', 'Automobilizam', 'Etapna auto-utrka?', 'Reli\nRally'),
('CROATIAN', 'Avijacija', 'Prvi masovno proizveden vojni zrakoplov u Njemackoj 1910.g.', 'Rumpler Taube'),
('CROATIAN', 'Banda', 'Najveca americka zatvorska banda Meksikanaca?', 'Nuestra Familia'),
('CROATIAN', 'Bande', 'Americka bjelacka rasisticka zatvorska banda koja cini oko 1% zatvorske populacije, ali je odgovorna za 26% ubojstava u zatvorskom sustavu?', 'Aryan Brotherhood\nThe Brand\nArijevsko bratstvo'),
('CROATIAN', 'Bankarstvo', 'Novac pozajmljen pod ugovornim uvjetima?', 'Kredit'),
('CROATIAN', 'Biblija', '"X" u "Xmas" oznacava grcku rijec za Krista (Christ), a to je ...?', 'Xristos'),
('CROATIAN', 'Biljke', 'Agresivna alergena biljka - pelud te biljke jedan je od najjacih poznatih alergena.', 'Ambrozija'),
('CROATIAN', 'Bilogija', 'Australska orhideja koja cvjeta ispod zemlje?', 'Rhizantela Rogers'),
('CROATIAN', 'Biologija', '"Biokemijska tvornica" naseg tijela je...?', 'Jetra'),
('CROATIAN', 'Bitke', 'Tromjesecna bitka u II. svj. ratu u kojoj je poginulo 12 000 Amerikanaca i 100 000 Japanaca?', 'Bitka za Okinawu'),
('CROATIAN', 'Bizarno', 'Americka tvrtka koja proizvodi umjetne dijamante od ugljika iz tijela?', 'LifeGem'),
('CROATIAN', 'Bizarnost', 'Argentinac E.Gomez kojega je usmrtila slucajna hrpa metala bio je poznat kao...?', 'Covjek magnet'),
('CROATIAN', 'Bizarnosti', 'Amerikanac A. Heckard je tuzio Michaela Jordana zbog emocionalnih trauma zato sto mu...?', 'Nalikuje'),
('CROATIAN', 'Bonton', 'Nakon odsvirane ili otpjevane drzavne himne se...?', 'Ne pljesce\nNe aplaudira'),
('CROATIAN', 'Bosanska poezija', '"Tako ti je mala moja kad ljubi..."...?', 'Bosanac'),
('CROATIAN', 'Botanika', 'Arboretum obitelji Bombelles u Vinici pokraj Varazdina.', 'Opeka'),
('CROATIAN', 'Casino', 'Koliko cete dobiti ako ste ulozili 50 zetona na dobitnu boju u ruletu?', '100'),
('CROATIAN', 'Citati', '"?ovjek se rodi slobodan, ali je posvuda u okovima."', 'Jean-Jacques Rousseau'),
('CROATIAN', 'Citati/Humor', 'Stipe Mesic: "U Drugom svjetskom ratu Hrvati su..."?', 'Dvaput pobijedili'),
('CROATIAN', 'Crni humor', 'Beogradski izraz za mlade motocikliste.', 'Donatori'),
('CROATIAN', 'Crtani film', 'Andele, andele, y''arriva, y''arriva, yeppa, yeppa....?', 'Speedy Gonzales'),
('CROATIAN', 'Crtici', '"Mislim da sam vidio micu macu"!Kafo fe fove mafa?', 'Silvester'),
('CROATIAN', 'Datum', 'Svjetski dan voda?', '22. ozujak'),
('CROATIAN', 'David Hasselhoff fan club', 'David je burno reagirao kada su ga u Baywatchu zamolili da? :)', 'depilira prsa'),
('CROATIAN', 'Deminutiv', 'Kost', 'Koscica'),
('CROATIAN', 'Destilacija', 'Jedina muslimanska destilerija koja vec 150 godina proizvodi pivo i whiskey (u danasnjem Pakistanu)...', 'Murree'),
('CROATIAN', 'Dijalekt', 'Dubrovacki izraz za prozor', 'Funjestra'),
('CROATIAN', 'Diplomacija', 'Punomoc kojom neka osoba postaje zastupnik interesa domovine u stranoj drzavi?', 'Akreditacija'),
('CROATIAN', 'Dizajn', 'Ime bezvremenog stolca kojega je 1958. dizajnirao Arne Jacobsen.', 'Egg chair\nEgg'),
('CROATIAN', 'Drustvo', 'Marginalna grupa sa radikalno drukcijim shvacanjem svijeta i nacinom zivota razlicitim od norme koja postoji u ostatku drustva?', 'Kult\nSekta'),
('CROATIAN', 'Egipatska mitologija', 'Kako se zovu dva divovska kamena kipa sto prikazuju faraona Amenofisa III?', 'Memnonovi kolosi'),
('CROATIAN', 'Ekologija', '"Eko sustav nalikuje zidu iz kojega covjek polako...!"?', 'Izbija cigle'),
('CROATIAN', 'Ekonomija', '"Povoljne su sve promjene koje cine da je nekima bolje ako zbog njih nije nekome drugome losije" nacelo je...?', 'Ekonomije blagostanja'),
('CROATIAN', 'Elektronika', 'Cetvrti svjetski proizvodjac mobitela.', 'Sony Ericsson'),
('CROATIAN', 'Elektrotehnika', 'Abecednim redom navedite tri elektrode bipolarnog tranzistora?', 'baza emiter kolektor'),
('CROATIAN', 'Energija', 'Predsjednik ruskog naftnog giganta Gazproma.', 'Alexei Borisovich Miller'),
('CROATIAN', 'Engleski', 'Akronimi Engleskog jezika MSGS.?', 'messages'),
('CROATIAN', 'Engleski jezik', 'Caj', 'Tea'),
('CROATIAN', 'Enigmatika', 'Krizaljka s opisima u rubnim poljima?', 'Skandinavka'),
('CROATIAN', 'Enologija', 'Autohtona bijela sorta iz Hercegovine?', 'Zilavka'),
('CROATIAN', 'Etnologija', 'Sator sjevernoamerickih Indijanaca sa Srednjeg Zapada...', 'Tipi'),
('CROATIAN', 'Europa', 'Naziv za ozivljavanje i ujedinjenje Italije u 19. st..', 'Risorgimento'),
('CROATIAN', 'Europska Unija', 'Cetvrti kriterij za ulazak u EU, utemeljen u Madridu.', 'Administrativni kriterij'),
('CROATIAN', 'Ezoterija', 'Energetski centri ljudskog tijela.', 'Cakre'),
('CROATIAN', 'Farmacija', 'Ime lijeka protiv alergije na ambroziju...', 'Lectranal'),
('CROATIAN', 'Fig. izrazi', 'Biti neskroman, traziti vise nego sto trebas = Traziti...?', 'Kruha svrh pogace'),
('CROATIAN', 'Film', '"Andaluzijski pas" je nadrealisticki film L. Bunuela i...?', 'Salvadora Dalija'),
('CROATIAN', 'Film i TV', 'Autor crtanih filmova "Macak Fritz" i "Gospodar prstenova".', 'Ralph Bakshi'),
('CROATIAN', 'Film â€“James Dean', 'Â«Istocno od...Â»?', 'raja'),
('CROATIAN', 'Film/Glazba', 'Filmska glazba kao dio filmske trake ili na posebnom nosacu zvuka (engl.).', 'Soundtrack'),
('CROATIAN', 'Film/Knjizevnost', 'Am. pisac, glumac i scenarist (Chuck Yeager u "The Right Stuff").', 'Sam Shepard'),
('CROATIAN', 'Film/Strip', 'Majka lutalica ga je na svijet donijela u podrumu tal. restorana "Mamma Leone" sto je obiljezilo njegove prehrambene navike.', 'Garfield'),
('CROATIAN', 'Film/Televizija', 'Hrv. glumac, ostvario niz komicnih uloga ("Prosjaci i sinovi", "Velo misto")?', 'Spiro Guberina'),
('CROATIAN', 'Filmske veze', 'Svestrani filmas s kojim su podijelile dio zivota B. Bardot, J. Fonda i C. Deneuve.', 'Roger Vadim'),
('CROATIAN', 'Filmski biseri', 'Film Bretta Ratnera "Rush hour" kod nas je preveden:', 'Gas do daske'),
('CROATIAN', 'Filmski citati', 'Kathy Bates ("Diabolique"): "Testosteron. Njime bi trebalo..."?', 'Puniti bombe'),
('CROATIAN', 'Filozofija', '"Bitak" je?', 'Ono po cemu jest sve sto jest'),
('CROATIAN', 'Fizicari', 'Danski fizicar: otkrio elektromagnetizam.', 'Hans Christian Oersted'),
('CROATIAN', 'Fizika', '"Ako je neko tijelo "A" u toplinskoj ravnotezi s tijelom "B" i s tijelom "C", onda su tijela "B" i "C" u medjusobnoj toplinskoj ravnotezi." Koji je to zakon?', 'Nulti zakon termodinamike'),
('CROATIAN', 'Fizika/Filozofija', 'Teorija deterministickog kaosa ili teorija...?', 'Nelinearne dinamike'),
('CROATIAN', 'Fobije', 'Antofobija.?', 'Strah od cvijeca'),
('CROATIAN', 'Folklor', 'Chileanski kauboj...', 'Huaso'),
('CROATIAN', 'Formula', 'Staza utrke u Italiji.', 'Imola'),
('CROATIAN', 'Formula 1', 'Finski vozac koji je 1982. osvojio prvenstvo uz jednu jedinu pobjedu...', 'Keke Rosberg'),
('CROATIAN', 'Fotografija', 'Americka fotografkinja portreta (John i Yoko, etc.)...', 'Annie Leibovitz'),
('CROATIAN', 'Francuski', 'C''est la vie!', 'Takav je zivot'),
('CROATIAN', 'Francuski jezik', 'Evo, eto.', 'Voila'),
('CROATIAN', 'Gastornomija', 'Ovo ulje vrlo je slicno maslinovom po kvaliteti i okusu, pa u azijskoj kuhinji ima jednako vaznu ulogu kao maslinovo u mediteranskoj?', 'ulje kikirikija'),
('CROATIAN', 'Gastro', 'Poznati talijanski aperitiv jarko crvene boje?', 'campari soda\ncamparisoda'),
('CROATIAN', 'Gastronomija', '"Pice nase i vase mladosti".', 'Cocta'),
('CROATIAN', 'Generali', 'General-geodet, bjegunac...', 'Vladimir Zagorac'),
('CROATIAN', 'Genetika', 'Puni naziv za DNK - nuklensku kiselinu u obliku dvostruke, spirano zavijene zavojnice koja sadri geneticke odrednice za specificni bioloski razvoj stanicnih oblika zivota i vecine virusa.', 'Deoksiribonukleinska kiselina'),
('CROATIAN', 'Geografija', '"Old faithful" ime je najpoznatijeg svjetskog?', 'Gejzira'),
('CROATIAN', 'Geografije', '"Ukusni" otoci koji pripadaju Velikoj Britaniji.', 'Otoci Juzni Sandwich otoci\nSouth Sandwich Islands'),
('CROATIAN', 'Geologija', 'Americki seizmolog po kojem je nazvana skala za mjerenje jacine potresa.', 'Charles Richter'),
('CROATIAN', 'Geometrija', 'Mnogokut sa 3 stranice?', 'trokut'),
('CROATIAN', 'Germanizmi', 'Znanost.', 'Wissenschaft'),
('CROATIAN', 'Glazba', '"...... they''re all doing the monster mash and most of the taxis and the wores are only taking calls for cash" Naslov ove pjesme Dire Straits-a?', 'Your latest trick'),
('CROATIAN', 'Glazba i Film', 'Americki pjevac i filmski glumac...?', 'Frank Sinatra'),
('CROATIAN', 'Glazba/Arheologija', 'Zenski ostatci australopiteka otkriveni u Etiopiji 1974. i nazvani "Lucy", svoje ime duguju pjesmi grupe koju su arheolozi slusali na dan pronalaska. O kojoj je grupi rijec?', 'The Beatles '),
('CROATIAN', 'Glazba/Film', 'Hrv. sopranistica, dobitnica nagrade M. Trnina; ipak je najvise pamtimo kao glumicu u filmu "Tko pjeva zlo ne misli"?', 'Mirjana Bohanec'),
('CROATIAN', 'Gluopst', 'Koju vrstu obuce ima Kip Slobode?', 'sandale'),
('CROATIAN', 'Glupost', '"Idealne" mjere zene', '90 60 90'),
('CROATIAN', 'Gluposti', 'Cijev je sipka kroz koju je provucena...', 'Rupa'),
('CROATIAN', 'Gospodarstvo', 'Americka fransiza restorana brze prehrane dekorirana kao americke zalogajnice iz 1940-ih i 50-ih?', 'Johnny Rockets'),
('CROATIAN', 'Gospodrastvo', 'Malezija potice proizovdnju palminog ulja zbog povecane potraznje za?', 'bio-dizelom'),
('CROATIAN', 'Graditeljstvo', 'Omanja cigla.', 'Briket\nBriketa'),
('CROATIAN', 'Gradjevinarstvo', 'Kada se izgrade sve planirane autoceste u Hrvatskoj, biti ce ih ukupno.', '11\njedanaest'),
('CROATIAN', 'Gradjevine', 'Bivsi dvor ceskih kraljeva,sada rezidencija ceskog predsjednika i vlade?', 'Hradcany'),
('CROATIAN', 'Gradovi', 'Prva apoteka na Balkanu i druga u Europi?', 'Dubrovnik'),
('CROATIAN', 'Grafit', 'Dobre su djevojke dobre, ali lose....?', 'jos bolje'),
('CROATIAN', 'Grafiti', '"Bog je stvoria covika, a Zadar...', 'kosarku'),
('CROATIAN', 'Gramatika', '10 i 1 slovo abecede', 'f a'),
('CROATIAN', 'Grbovi', 'Krunu od pet siljaka na stitu sa sahovnicom zapravo cini pet...?', 'Povijesnih hrvatskih grbova'),
('CROATIAN', 'Grcka mitologija', 'Boginja (Bog) trenutne srece je ...', 'Kairos\nKaira'),
('CROATIAN', 'Grcki', 'Pcela?', 'melissa'),
('CROATIAN', 'Heraldika', 'Grb Licko-senjske zupanije na sebi ima zlatni cvijet ...', 'Degenije'),
('CROATIAN', 'Hobi', 'Sto skuplja filuminist?', 'kutije sibica'),
('CROATIAN', 'Hokej', 'Najjaci hrvatski hokejski klub', 'Medvescak'),
('CROATIAN', 'Homonimi', 'Baka u cakavskim krajevima, a nocna posuda u sjevernim.', 'Nona'),
('CROATIAN', 'Horoskop', 'Ako ste rodjeni na Novu Godinu, sto ste po horoskopu?', 'Jarac'),
('CROATIAN', 'Hrana', 'Autohtoni punomasni mekani hrvatski sir koji se proizvodi iz toplinski neobradjenog mlijeka.', 'Skripavac'),
('CROATIAN', 'Hrvatske tvrdjave', 'Dubrovacka?', 'Revelin'),
('CROATIAN', 'Hrvatski jezik', 'Posvojni pridjevi izvedeni od imena naseljena mjesta.', 'Ktetici'),
('CROATIAN', 'Hrvatski knezevi', 'Kronoloski ide Borna, Vladislav pa...?', 'Mislav'),
('CROATIAN', 'Humor', '"Cinjenica: Neki ljudi tvrdili su da je Chuck Norris izmisljotina. Vise nisu ..."?', 'Medju zivima'),
('CROATIAN', 'Igra', 'Najmanje vrijedna pikula.', 'obicnjaca'),
('CROATIAN', 'Igre', 'Igra bacanja plosnatog kamena koji bi trebao nekoliko puta odskociti na povrsini vode?', 'Zabica\nZabice'),
('CROATIAN', 'Imena', 'Ime Ana dolazi od hebr. imena Hannah sto znaci...?', 'milost'),
('CROATIAN', 'Industrija', 'Britanski Cornwall medjuostalome je poznat po vrijednim nalazistima...', 'kaolina'),
('CROATIAN', 'Informatika', '.koje godine je osnovana tvrtka Apple Computers?', '1975'),
('CROATIAN', 'Institucije', 'Institucija medjuregionalne suradnje na gotovo svim nepolitickom podrucjima (Hrvatska, Slovenija, Austrija...)?', 'Alpe-Jadran'),
('CROATIAN', 'Integracije', 'Program NATO-a za postupnu pripremu svojih buducih clanica.', 'Partnerstvo za mir'),
('CROATIAN', 'Internet', '"Very Easy Rodent Oriented Net-wide Index to Computerised Archives" - programski alat za trazenje datoteka na Internetu ili ukratko ...', 'Veronica'),
('CROATIAN', 'Istrazivanja', 'Cak 81 % muskaraca misli da su brinete prije svega...?', 'Inteligentne'),
('CROATIAN', 'Izbaci uljeza', 'Domino, jamb, monopoly, covjece ne ljuti se!', 'domino'),
('CROATIAN', 'Izdavastvo', 'Am. pandan nasem casopisu "Sam" ("Uradi sam").', 'Make'),
('CROATIAN', 'Izjave slavnih', 'Albert Einstein: Ako je A uspjeh u zivotu, onda je A = x plus y plus z. X je rad, Y je igra, Z je ...', 'Drzanje jezika za zubima'),
('CROATIAN', 'Izreke', '"Cuius regio, illius regio" u prenesenom znacenju danas znaci: Pokoravaj se zakonima...?', 'Zemlje u kojoj zivis'),
('CROATIAN', 'Izumi', 'BBB mogu biti zahvalni izumitelju dinama koji se zvao...', 'Michael Faraday'),
('CROATIAN', 'Jeste li znali', 'Svi polarni medvjedi su .........!', 'ljevoruki'),
('CROATIAN', 'Jezici', '"Badnjak" na spanjolskom jeziku.', 'Nochebuena'),
('CROATIAN', 'Jezik', '"Ilica" ("Ilidza") na turskom znaci ...', 'Izvor tople vode'),
('CROATIAN', 'Jezikoslovlje', 'Lingvist koji proucava jezicno znakovlje?', 'Semioticar'),
('CROATIAN', 'Kalendar', 'Koliko je 1976. godina imala dana?', '366'),
('CROATIAN', 'karikatura', 'Lik iz nekad svakodnevnih karikatura Ismeta Voljevice.', 'Grga Protokol'),
('CROATIAN', 'Kartografija', 'Linije koje na geografskim kartama spajaju mjesta jednakih srednjih godisnjih temperatura?', 'Hidroizoterme'),
('CROATIAN', 'Katastrofe', 'Indijski grad Bhopal 3.12.1984.g. iz tvornice pesticida ''Union Carbide'' poharan je istjecanjem 40t otrovnog plina...', 'Metil izocijanat'),
('CROATIAN', 'Kazaliste', 'Cvjetni prolaz u japanskim kazalistima koji spaja rubove pozornice s dnom gledalista?', 'Hanamichi'),
('CROATIAN', 'Kazaliste/Film', 'Mjuzikl "My fair lady" je nastao prema komediji G.B.Shawa ...', 'Pigmalion'),
('CROATIAN', 'Kemija', '"Alkoholnim vrenjem" nastaje alkohol poznat pod imenom?', 'etanol'),
('CROATIAN', 'Kinologija', 'Pasmina iz Romagne poznata po trazenju tartufa.', 'Lagotto Romagnolo'),
('CROATIAN', 'Kiparstvo', 'Hrvatski kipar (mauzolej Petra Petrovica Njegosa).', 'Ivan Mestrovic'),
('CROATIAN', 'Kjizevnost', 'Roman koji je Robert Louis Stevenson napisao pod utjecajem kokaina u sest dana i sest noci?', 'The Strange Case of Dr. Jekyll and Mr. Hyde'),
('CROATIAN', 'Kjnizevnost', 'Najstariji sacuvani ep na engleskom jeziku?', 'Beowulf'),
('CROATIAN', 'Knizevnost', 'Knjiga J.R.R. Tolkiena, slikovnica o nevoljama iz zivota Djeda Mraza.', 'The Father Christmas Letters\nPisma Djeda Mraza'),
('CROATIAN', 'Knjige', 'Ime dobrocudnog poludiva iz Harry Potter-a?', 'Hagrid'),
('CROATIAN', 'Knjiizevnost', 'Vrhunac Shakespeareovog opusa cetiri su velike tragedije: Hamlet, Otelo, Macbeth i ...?', 'Kralj Lear\nKing Lear'),
('CROATIAN', 'Knjizevnost', '"Ala je lep ovaj svet!" uzviknuo je baĹˇ on.', 'Jovan Jovanovic Zmaj'),
('CROATIAN', 'Knjizevnost / glazba', 'Epski pjevaci u staroj Grckoj?', 'Aedi i rapsodi'),
('CROATIAN', 'Knjizevnost/Film', 'Francuski "pjesnik Pariza" ("Barbara") i scenarist ("Obala u magli")?', 'Jacques Prevert'),
('CROATIAN', 'Knjizevnost/glazba', 'Dr. Faust je Mefistu prodao dusu da bi zauzvrat dobio...?', 'Bogatstvo i mladost'),
('CROATIAN', 'Knjizevnost/Politika', 'Senegalski pjesnik i politicar, predsjednik drzave 1960.-1980.?', 'Leopold Sedar Senghor'),
('CROATIAN', 'Knjizevost', 'Dovrsi stih Emily Dickinson "Bas onaj tko nije nikada iskusio odredjene osjecaje, vec je samo za njima ceznuo..."', 'Razumije ih u njihovoj punini'),
('CROATIAN', 'Knjizvenost', 'Groteskna pojava u komediji dell''arte, prozdrljiv i drzak lik, koji svakome kaze istinu u lice.', 'Pulcinella'),
('CROATIAN', 'Knjzevnost', 'Koje je pravo ime knjizevnika Ksavera Sandora Gjalskog?', 'Ljubomir Babic\nLjubo Babic'),
('CROATIAN', 'Kokteli', 'Koktel ciji su glavni sastojci rum, sok od ananasa i kokosovo mlijeko.', 'Pina colada'),
('CROATIAN', 'Komentatori', 'Milojko Pantic na derbiju Partizan - Crvena zvezda: "Evo izlaze igraci Partizana, a evo i..."?', 'nasih'),
('CROATIAN', 'Kratice', 'Anoniman autor - N.N.?', 'Nomen nescio'),
('CROATIAN', 'Kriminal', 'Flunitrazepam (tvornickog imena Rohypnol) nosi ulicno ime ...', 'Droga za silovanje'),
('CROATIAN', 'Kriminalistika', 'Osim otiska prstiju, jedinstven je i otisak ...', 'jezika'),
('CROATIAN', 'Kriminologija', 'U SAD-u se ubojstvo dogodi svake .. minute.', '23'),
('CROATIAN', 'Kuhanje', 'Tradicionalna istarska hrana od vina i kruha', 'Istarska supa'),
('CROATIAN', 'Kulinarstvo', 'Aromaticni plod tropskog drveta, stavlja se kao zacin u razna slatka i slana jela, morski orascic ili ...', 'Muskatni orascic'),
('CROATIAN', 'Kultura', '"Rugao se lonac loncu, a oba su...', 'crna'),
('CROATIAN', 'Kutura', 'Kako se zove prva zena primljena u Akademiju znanosti i umjetnosti?', 'Ivana Brlic Mazuranic'),
('CROATIAN', 'Kviz', 'biseri - Quizzard: Botanika - Uzgoj ruza.Tomi_G:', 'ruzarenje'),
('CROATIAN', 'Kviz biseri', 'Quizzard: Tehnologija - Riblje oko je sto?  _tantrum_:', 'kao macije'),
('CROATIAN', 'Kviz. biseri', 'Sjetva ili...? Master_Di: ...?', 'Kosidba'),
('CROATIAN', 'Kvizerski biseri', 'Administrativna teritorijalna jedinica u Francuskoj? pantagana: ...?', 'Depadansa'),
('CROATIAN', 'Latinizmi', 'Lupus in fabula?', 'vuk u prici'),
('CROATIAN', 'Latinska poslovica', 'Quot capita, tot sententiae.', 'Koliko glava, toliko misljenja'),
('CROATIAN', 'Latinske izreke', 'Ad calendas graecas.', 'Kad na vrbi rodi grozdje'),
('CROATIAN', 'Latinski', '"Ad Lib" je kratica za "Ad libitum" sto znaci ...?', 'Sa zadovoljstvom'),
('CROATIAN', 'Legende', 'Ceh je utemeljio Cesku, Leh Poljsku, a Meh...?', 'Rusiju'),
('CROATIAN', 'Lezik', 'Dva samoglasnika koja se izgovaraju zajedno, dvoglas ili...?', 'Diftong'),
('CROATIAN', 'Likovna umjetnost', '"Arnolfini i njegova zena" slika je koju je 1434.g. naslikao?', 'Jan van Eyck'),
('CROATIAN', 'Lingvistika', 'Blazi izraz koji se rabi umjesto nepristojnih, neugodnih, ruznih ili opasnih izraza?', 'Eufemizam'),
('CROATIAN', 'Lingvistikai', 'Lat. Indijska konoplja.', 'Cannabis sativa'),
('CROATIAN', 'Linux', 'Distribucija koja se koristi na Konzumovim blagajnama?', 'Red Hat'),
('CROATIAN', 'Ljepota matematike', '11111 x 11111 =', '123 454 321'),
('CROATIAN', 'Ljubavne veze', 'Frank Sinatra i prva dama koja nedostaje: Ava, Lauren, Mia, Rafaella, Juliet, Barbara i...?', 'Nancy'),
('CROATIAN', 'Ljuti protivnici', 'Ben Hur vs.?', 'Mesala'),
('CROATIAN', 'Logika', 'Kako se naziva istinosna funkcija koja je istinita kad je njen argument lazan, i lazna kad je njen argument istinit?', 'Negacija'),
('CROATIAN', 'Lov', 'Dozivanje zivotinja imitiranjem njihovog glasanja?', 'vabljenje'),
('CROATIAN', 'Ludi zakoni', 'Ako ste neudani u Floridi i zelite se provesti nedjeljom, to ne smije bit skakanje ...', 'Padobranom'),
('CROATIAN', 'Lutkarstvo', 'Lutka koja se pokrece pomocu konaca o kojima visi?', 'Marioneta'),
('CROATIAN', 'Manifestacije', 'Koncert odrzan 2007. na 7 kontinenata sa svrhom upozorenja na pogubne ekoloske promjene.', 'Live earth'),
('CROATIAN', 'Marketing', 'Zastitni znak poduzeca ili proizvoda, najcesce strogo definiran knjigom standarda...', 'Logo'),
('CROATIAN', 'Marketinski slogani', '"Apple Computer"', 'Think different'),
('CROATIAN', 'Matematika', '''-'' je znak oduzimanja; ''='' je znak jednakosti, a 3 crtice jedna ponad druge je znak ...', 'kongruencije'),
('CROATIAN', 'Medecina', 'Muska spolna zlijezda kroz koju prolazi mokracna cijev...?', 'Prostata'),
('CROATIAN', 'Medicina', '"Crna smrt".', 'Kuga'),
('CROATIAN', 'Medicini', 'Lijecnici specijalisti za ozljede.', 'Traumatolozi'),
('CROATIAN', 'Mediji', 'Cuvena komentatorica sportskih priredbi (umjetnicko klizanje, atletika), sada u mirovini.', 'Milka Babovic'),
('CROATIAN', 'Mehanika', 'Mehanicki zglob.', 'kardan'),
('CROATIAN', 'Meteorologija', 'Japanski meteorolog prema kojem je nazvana ljestvica za stupnjevanje tornada?', 'Tetsuyi Fujiti'),
('CROATIAN', 'Mikrobiologija', 'Cista mikrobna kultura ili?', 'monokultura'),
('CROATIAN', 'Militarizacija', 'Ruski energetski giganti kojima je Duma odobrila stvaranje vlastitih korporacijskih vojski...', 'Gazprom i Transneft'),
('CROATIAN', 'Minerali', 'Crveni dragulj, vrsta mineralnog korunda (aluminijevog oksida) u kojem crvena boja potjece od kroma?', 'Rubin'),
('CROATIAN', 'Mineralogija', 'Dragi kamen po tvrdoci odmah iza dijamanta.', 'Korund'),
('CROATIAN', 'Misli', 'Mark Eyskens:"EU je gospodarski div, vanjskopoliticki patuljak i crv na podrucju..?', 'Sigurnosne politike'),
('CROATIAN', 'Mitologija', 'Adonisova majka?', 'Mirha'),
('CROATIAN', 'Mitovi', 'Jazonov brod je prozvan Argo po njegovu...?', 'Graditelju'),
('CROATIAN', 'Mjere', 'Sto kilograma, kvintal ili..?', 'Metricka centa'),
('CROATIAN', 'Mobilna tehnologija', 'Znacenje kratice CLIP.', 'Caller Line Identification Presentation'),
('CROATIAN', 'Mobiteli', 'Dual-Band mobiteli rade na frekvencijama..', '900 1800'),
('CROATIAN', 'Moda', 'Americki modni casopis osnovan 1867. godine i danas jedan od najpoznatijih na svijetu?', 'Harper''s Bazaar'),
('CROATIAN', 'Monarhije', 'Posljednji apsolutisticki monarh Afrike, kralj Svazilanda...', 'Mswati III'),
('CROATIAN', 'Mostogradnja', 'Stubovi nosaci velikih razmjera...', 'Piloni'),
('CROATIAN', 'Motocikli', '"Nadimak" Hondinih naked modela CB-600F i CB-900F.', 'Hornet'),
('CROATIAN', 'Motociklizam', 'Hondin supersportski motocikl CBR-1000RR?', 'Fireblade'),
('CROATIAN', 'Mudre izreke', '"Kad si sretnan i sunce za tobom zuri".', 'Ivana Brlic Mazuranic'),
('CROATIAN', 'Mudrosti', '"Nista zemaljsko nije vrijedno velike zelje" - autor je ...', 'Arthur Schopenhauer'),
('CROATIAN', 'Murpheyevi zakoni', 'Svatko bi trebao vjerovati u nesto, ja vjerujem da cu ...', 'Popiti jos jedno pice'),
('CROATIAN', 'Murphyjevi zakoni', 'Ako ti se cini da je sve u redu...', 'Nesto ti je promaknulo'),
('CROATIAN', 'Muzika', '1988. godine Celine Dion je na Eurosongu zastupala koju zemlju?', 'svicarsku\nsvicarska'),
('CROATIAN', 'Nadopuni', '"Covjece pazi da ne ides malen ispod ..."?', 'zvijezda'),
('CROATIAN', 'Nakit', 'Dijamant brusen s mnogobrojnim facetama kojima se postize sjaj i rasprsenje bijele svjetlosti?', 'Briljant'),
('CROATIAN', 'Navodno', 'Ako ste tuzni i usamljeni, pomoci ce ako zidove obojite...?', 'Narancasto'),
('CROATIAN', 'Nazivi', 'Koji pisac je prvi uveo rijec ROBOT u upotrebu?', 'Karel Capek'),
('CROATIAN', 'NBA', 'Domicil Timberwolvesa.', 'Minnesota'),
('CROATIAN', 'Neurologija', 'Nepodnosljiva napetost koju bolesnik umanjuje ponavljanjem iste radnje, rijeci ili misli?', 'Kompulzivna opsesija'),
('CROATIAN', 'NHL Timovi', 'Anaheim?', 'Mighty Ducks'),
('CROATIAN', 'Njemacki', 'Avion.', 'Flugzeug'),
('CROATIAN', 'Njemacki jezik', 'Verboten!', 'Zabranjeno'),
('CROATIAN', 'Nogomet', 'Arthur Antunes Coimbra, desetka brazilske reprezentacije, nasljednik velikog Pelea, poznatiji kao...', 'Zico'),
('CROATIAN', 'Novac', 'Sto se nalazi na nalicju kovanice od 1 kune?', 'slavuj'),
('CROATIAN', 'Novinarstvo', '"Globusova" kolumnistica koja posprdno komentira dnevnopoliticke dogadjaje.', 'Tanja Torbarina'),
('CROATIAN', 'Nutricionizam', 'Jedno od povrca koje ima negativne kalorije?', 'celer'),
('CROATIAN', 'Obicaji', '"Dijete Isus" koje tradicionalno na Bozic donosi darove djeci u Njemackoji i Austriji.', 'Kristkind\nKristkindl'),
('CROATIAN', 'Obrazovanje', 'Obrazovni stupanj koji odgovara visoj skoli, VI. stupanj.', 'Bakalaureat'),
('CROATIAN', 'Obrt', 'Fini mrezasti rad od srebrne ili zlatne zice, slican cipki...', 'Filigran'),
('CROATIAN', 'Odgovori', 'Gdje?', 'ovdje\nondje\ntamo'),
('CROATIAN', 'Odlicja', 'Ciji lik nosi Red Danice hrvatske koji se dodjeljuje za osobite zasluge u gospodarstvu?', 'Blaza Lorkovica\nBlaz Lorkovic'),
('CROATIAN', 'Opca kultura', 'Kako glasi slogan Europske unije?', 'In varietate concordia\nUjedinjeni u raznolikosti'),
('CROATIAN', 'Opcenito', 'Kako nazivamo razliku izmedju stope radjanja i stope umiranja?', 'stopa prirodnog prirastaja'),
('CROATIAN', 'Organizacije', 'FAO je organizacija UN koja se brine za ...?', 'Poljoprivredu i prehranu'),
('CROATIAN', 'Oruzja', 'Bojna indijanska sjekira?', 'Tomahawk'),
('CROATIAN', 'Oruzje', '"Sluzbeni nadimak" americkog lovca F-16?', 'Fighting Falcon'),
('CROATIAN', 'Osobe', 'Poznati moderni slikar. Dizajnirao Alien-a', 'H.R. Giger'),
('CROATIAN', 'Otrov', 'Alkaloid iz sjemena stabla Strychnos Nux-Vomica poznat nam je pod nazivom ...', 'Strihnin'),
('CROATIAN', 'Oznake', '!', 'usklicnik'),
('CROATIAN', 'Palindromi', 'Da ili ne - A?', 'da'),
('CROATIAN', 'Parapsihologija', 'Izvanosjetilno prenosenje psihickih procesa jedne osobe drugoj.', 'Telepatija'),
('CROATIAN', 'Parovi', 'Romeo i ...', 'Julija\nJulia'),
('CROATIAN', 'Pismo', 'Dvoslovi hrvatske abecede?', 'dz lj nj'),
('CROATIAN', 'Pitalica', 'Imate kutiju s jednom sibicom i ulazite u hladnu i mracnu prostoriju u kojoj se nalaze svijeca, petrolejka i pec. Sto cete prvo upaliti?', 'Sibicu'),
('CROATIAN', 'Pitanje', 'Skandinavske zemlje imaju iste zastave samo razlicitih boja. DA ili NE?', 'DA'),
('CROATIAN', 'Pjesmica', 'Pisi, risi, ali znaj...?', 'listove mi ne trgaj'),
('CROATIAN', 'Ples', 'Egzotican folklorno-zabavni ples slican merengueu i brazilskoj sambi.', 'Tambor'),
('CROATIAN', 'Plovidba', 'Glavni uzduzni konstrukcijski element broda; proteze se od pramca do krme sredinom dna broda?', 'kobilica'),
('CROATIAN', 'Politicari', 'Bolivijski predsjednik...', 'Evo Morales'),
('CROATIAN', 'Politicki humor', 'Naziv za stranke u RH koje se registriraju netom prije izbora, s vrlo kratkim rokom "uporabe"?', 'Paloma stranke'),
('CROATIAN', 'Politika', '"Lijepa nasa" je postala sluzbenom himnom tadasnje SRH tek godine ...', '1972.\n1972'),
('CROATIAN', 'Politika i gospodarstvo', 'Robert Schuman i Jean Monnet su idejni zacetnici...?', 'Europske unije'),
('CROATIAN', 'Poljoprivreda', 'Rijeka na cijoj delti se u Europi uzgaja riza.', 'Rhone'),
('CROATIAN', 'Pomorstvo', 'Brik kojim je kapetan Ivan Visin iz Prcnja oplovio svijet?', 'Splendido'),
('CROATIAN', 'Porno', '80-ih i 90-ih vrlo popularna porno glumica.', 'Amber Lynn'),
('CROATIAN', 'Pornografija', 'Glavna glumica u kultnom pornicu ''Duboko Grlo''?', 'Linda Lovelace'),
('CROATIAN', 'Poslovica', 'Po jutru se ...?', 'Dan poznaje'),
('CROATIAN', 'Poslovice', '"Bleji u sarena vrata"?', 'Tele'),
('CROATIAN', 'Povijest', '"Izgubljeni grad" Inka?', 'Machu Picchu'),
('CROATIAN', 'Povijest EU', 'Koji prirodni resursi su najprije stavljeni pod zajednicku upravu?', 'Ugljen i celik'),
('CROATIAN', 'Povijest filma', 'Koje godine je George Eastman prvi put predstavio film u boji?', '1929'),
('CROATIAN', 'Povijest umjetnosti', 'Imitiranje gotike s kraja 19. i pocetka 20. st.?', 'Pseudogotika'),
('CROATIAN', 'Povijest/Knjizevnost', 'Putopis Alberta Fortisa iz 18. stoljeca u kojem opisuje nasu obalu.', 'Put po Dalmaciji'),
('CROATIAN', 'Povjest', 'Gdje je osnovan prvi partizanski odred?', 'Sisak'),
('CROATIAN', 'Povrce', 'Maslasta salata ili ...', 'Salata puterica'),
('CROATIAN', 'Poznate zadnje rijeci', 'Ne bi valjda udario cojeka sa .........?', 'naocalama'),
('CROATIAN', 'Poznati parovi', 'Ante Kostelic i?', 'Marica Kostelic'),
('CROATIAN', 'Pravo', '"Krajnjom nuzdom" se smatra ucinjeno zlo koje ne smije biti vece od onog koje je...?', 'Prijetilo'),
('CROATIAN', 'Pravopis', 'Bezvucni parnjak suglasniku d.', 'T'),
('CROATIAN', 'Predaja', 'Po narodnom vjerovanju ucenik koji zavrsi i 13., vrazju godinu skolovanja?', 'Grabancijas'),
('CROATIAN', 'Prehrana', 'Kako se nazivaju vegetarijanci koji izbjegavaju crveno meso, a konzumiraju piletinu i ribu?', 'Semivegetarijanci'),
('CROATIAN', 'Premetaljka', 'Kompjuterska terminologija "Crim"?', 'mIRC'),
('CROATIAN', 'Prevedite', 'najbolji(eng)', 'the best'),
('CROATIAN', 'Prijevod', 'Na engleskom naziv za lovackog psa?', 'hound'),
('CROATIAN', 'Prijevodi', 'Gaudeamus u prijevodu znaci ...?', 'Veselimo se'),
('CROATIAN', 'Priroda', '"Struk" biljke?', 'Vlat'),
('CROATIAN', 'Profesorski biseri', 'Profesor zemljopisa: Znajte, glavni grad mora biti glavni grad inace je ...', 'Sporedan'),
('CROATIAN', 'Programiranje', 'Ansi C funkcija za inicijalizaciju generatora slucajnog broja??', 'srand'),
('CROATIAN', 'Proizvodi', 'Po cemu je poznat grad Lepoglava?', 'po cipki'),
('CROATIAN', 'Promet', 'Brzina (km/h) koju je u srpnju 1976. postigao Lockheedov SR-71A?', '3529'),
('CROATIAN', 'Pseudonimi', 'Bird', 'Charlie Parker'),
('CROATIAN', 'Psihogija', 'Seksualna nastranost istovremene masturbacije i samogusenja, gdje je zadovoljstvo navodno povecano zbog povecane produkcije endorfina u stanju blizu gusenja?', 'Autoerotska asfiksijacija'),
('CROATIAN', 'Psihologija', '"Iskreni" osmijeh cije je obiljezje pomicanje kruznog ocnog misica?', 'Duchenneov osmijeh'),
('CROATIAN', 'Psiholohija', 'Najutjecajniji psiholog 20. stoljeca.', 'Burrhus Frederic Skinner\nSkinner'),
('CROATIAN', 'Ptice', 'Dugovrata ptica iz reda guscarica.', 'Labud'),
('CROATIAN', 'Publicistika', 'Naslov knjige u kojoj W.Engdahl iznosi teoriju zavjere po kojoj je GMO izmisljen radi smanjenja ljudske populacije.', 'Sjeme unistenja'),
('CROATIAN', 'Quiz biseri', 'Quizzard: Indijanski narod ciju drzavu unistava conquistador Cortes. ..nicola1:', 'hindu'),
('CROATIAN', 'Quizz biseri', 'Poslovice: riba ribi...? Tomi G:...', 'Sam u nju pada'),
('CROATIAN', 'Racunala', 'Godina formiranja Motorola kompanije (orginalno Galvin Manufacture Co)?', '1928'),
('CROATIAN', 'Racunalstvo', '"Warez" se odnosi na kakav software?', 'ilegalni'),
('CROATIAN', 'Racunari', 'Drugi naziv za knjigu "Common LISP: The Language"?', 'Aluminum book'),
('CROATIAN', 'Racunarsto', 'Tvrtka specijalizirana za proizvodnju sportskih simulacija (''NBA live'', ''Fifa'')', 'Electronic Arts'),
('CROATIAN', 'Racunarstvo', '"The X-Y Position Indicator For A Display System" ili koji hardverski prototip iz 1963.g.?', 'Mis'),
('CROATIAN', 'Radio', 'Koja radio drama je uzrokovala kaos u Americi?', 'Rat svjetova'),
('CROATIAN', 'Rano', 'Kako nazivaju Djeda Mraza u njegovoj domovini Laponiji?', 'Joulupukki'),
('CROATIAN', 'Rasa', 'Plava krv oznacava pripadnike koje klase?', 'plemstvo\nplemstva'),
('CROATIAN', 'Rat', 'Kamikaze se ne na neprijatelja obrusava avionom, tko juri u smrt torpedom?', 'kaiten'),
('CROATIAN', 'Ratovanje', 'Britanske padobranske postrojbe za posebne namjene?', 'Paras'),
('CROATIAN', 'Ratovi', 'Kako je nazvan sukob izmedju SAD i  SSSR poslije 1945. godine', 'Hladni rat'),
('CROATIAN', 'Razgovori', 'Obilaziti oko teme u razgovoru', 'okolisati'),
('CROATIAN', 'Raznno', 'Hrvatski botanicar iz Malog Losinja cija se bogata herbarska zbirka cuva u Botanickom zavodu PMF-a u Zagrebu.', 'Ambroz Haracic'),
('CROATIAN', 'Razno', '"7X" je predstavljao tajni sastojak kojeg pica?', 'Coca-Cole\nCoca-Cola'),
('CROATIAN', 'Registracije', 'Registarska oznaka Belog Manastira', 'Bm'),
('CROATIAN', 'Reklame', '...Bilo kuda kiki..."?', 'Svuda'),
('CROATIAN', 'Rekorderi', 'Svjetski rekorder u voznji automobilom, poginuo u "plavoj ptici" pri brzini od 960km/h?', 'Donald Campbell'),
('CROATIAN', 'Rekordi', 'Kako se zvalo plovilo kojim je 20.11.1977. postavljen trenutno vazeci svjetski brzinski rekord na vodi?', 'Spirit Of Australia'),
('CROATIAN', 'Rekreacija', 'Muski rekord u penjanju do vrha stubista Empire State Buildinga iznosi...', '573 sekunde'),
('CROATIAN', 'Religija', '"Cisterciti strozeg obreda" poznatiji su nam po imenu ...', 'Trapisti'),
('CROATIAN', 'Religije', 'Skola Mahayana budizma na Dalekom istoku?', 'Zen'),
('CROATIAN', 'Ribarstvo', 'Mreza potegaca za lov gira?', 'Migavica'),
('CROATIAN', 'Rijeci', 'Arhaicni regionalizam za rijec zgrabiti (Ljubo Cesic Rojs)...?', 'Jamiti'),
('CROATIAN', 'Rimski brojevi', '1268?', 'mcclxviii'),
('CROATIAN', 'Robotika', 'Covjekoliki robot.', 'Android'),
('CROATIAN', 'Rudarstvo', 'Rudarska ili ... svjetiljka.', 'Davyjeva'),
('CROATIAN', 'Ruski', 'Istina?', 'pravda'),
('CROATIAN', 'Sah', 'Cetvrti sahovski svjetski prvak, doktor prava i ruski aristokrat.', 'Aleksandar Aljehin\nAleksandar Aleksandrovic Aljehin'),
('CROATIAN', 'Sala', 'Boji se macaka :)?', 'Mis'),
('CROATIAN', 'San svakog muskarca', 'Netaknuta djevica (lat.).', 'Virgo intacta'),
('CROATIAN', 'Satelitska terminologija', 'Brzina digitalnog prijenosa, obicno se izrazava u Mb/s.', 'Bit rate'),
('CROATIAN', 'Scena', 'Ministar vanjskih poslova "Republike Pescenice".', 'Seva'),
('CROATIAN', 'Seksizam', 'Pametniji i jaci spol.', 'Muski'),
('CROATIAN', 'Seksologija', 'Kulminacijska tocka spolnog odnosa.', 'Orgazam'),
('CROATIAN', 'Serija', 'Star Trek: Zemlja podrijetla Williama Rikera.', 'Aljaska'),
('CROATIAN', 'Serije', 'Americka glumica poznata po ulozi Betty Suarez u americkoj sapunici ''Ugly Betty''.', 'America Ferrera\nAmerica Georgine Ferrera'),
('CROATIAN', 'SF', 'Ime klase kojoj pripada Enterprise-B?', 'excelsior'),
('CROATIAN', 'Simboli', 'Koju drzavu simbolizira tulipan?', 'Nizozemsku\nNizozemska'),
('CROATIAN', 'Sinomimi', 'Les.', 'Kadaver'),
('CROATIAN', 'Sinonim', 'Nadzornik.', 'Supervizor'),
('CROATIAN', 'Sinonimi', '"Kljuc za Indiju"', 'Sueski kanal'),
('CROATIAN', 'Skolstvo', 'Prostorija za skolsku nastavu', 'Ucionica'),
('CROATIAN', 'Skracenice', '"Drzavni zavod za proizvodnju lijekova i vakcina" nama je poznatiji kao...?', 'Pliva'),
('CROATIAN', 'Slang', 'Popricati s nekim?', 'baciti spiku\nbaciti sprehu'),
('CROATIAN', 'Slastice', 'Punjeni cokoladni bomboni', 'praline'),
('CROATIAN', 'Slavenska mitologija', 'Legendarni Istocnoslavenski zli kucni duh koji se pojavljuje u liku malene zene koja brine o domacim zivotinjama, a neprijateljski je raspolozena prema muskarcima, te nocu uznemirava djecu.', 'Kikimora'),
('CROATIAN', 'Slavni', 'Frank Sinatra je bio slavni americki?', 'pjevac'),
('CROATIAN', 'Slavni parovi', 'Glumica i monarh.', 'Grace Kelly i Reinier III'),
('CROATIAN', 'Slicnosti', 'Kineska igra slicna dominu.', 'Mahjong'),
('CROATIAN', 'Slikari', 'Najslavniji katalonski slikar.', 'Salvador Dali'),
('CROATIAN', 'Slikarstvo', 'Austrijski slikar, predstavnik ekspresionizma', 'Oskar Kokoschka'),
('CROATIAN', 'Slogani', 'Nadopunite: "Bacite peglu kupite ..."?', 'tico'),
('CROATIAN', 'Smijesane rijeci', 'cixeom?', 'Mexico'),
('CROATIAN', 'Smisao Zivota', 'Zasto igramo ovaj kviz?', 'jer nam je dosadno\njer nam je dosadno'),
('CROATIAN', 'Smjesane rijeci', 'Broj "Rit"?', 'tri'),
('CROATIAN', 'Smjesne stvari', 'Dobitnica ovogodisnje nagrade Ine u iznosu od 50 000 kuna za promicanje hrvatske kulture u svijetu.', 'Mirjana Sanader'),
('CROATIAN', 'Sociologija', 'Autoritarizam se razlikuje od totalitarizma zbog svoje manje ideoloske...', 'indoktriniranosti'),
('CROATIAN', 'Software', 'Najbolji i najpopularniji software za obradu slike?', 'Photoshop'),
('CROATIAN', 'Speleologija', 'Najdublja jama u Hrvatskoj (1392 m)?', 'Lukina jama'),
('CROATIAN', 'Sport', '"Bozja ruka".', 'Diego Maradona'),
('CROATIAN', 'Sport MLB', 'Nadopunite Anaheim ...?', 'Angels'),
('CROATIAN', 'Sport NFL', 'Nadopunite Arizona ...?', 'Cardinals'),
('CROATIAN', 'Sport NHL', 'Anaheim ...', 'Ducks'),
('CROATIAN', 'Stadioni', 'Stadion na kojem igra Bologna', 'Dall''Ara'),
('CROATIAN', 'Stanovnistvo', 'Anticki stanovnici Skotske.', 'Pikti'),
('CROATIAN', 'Star Trek', 'Glumac koji je glumio Dr. McCoya', 'DeForrest Kelley'),
('CROATIAN', 'Star Wars', 'Glumio Obi-Wan Kenobija u "Phantom Menace"', 'Ewan McGregor'),
('CROATIAN', 'Stari zanati', 'Onaj koji krpa stare lonce obilazeci kucanstva?', 'Kotlokrpa'),
('CROATIAN', 'Stihovi', 'Dovrsi: "Oprosti mi ..."', 'pape'),
('CROATIAN', 'Strahovi', 'Androfobia je strah od?', 'muskaraca'),
('CROATIAN', 'Strane rijeci', 'Holizam dolazi od grcke rijeci holos sto znaci?', 'cijel\npotpun'),
('CROATIAN', 'Strani jezici', 'Ako se u Italiji zovete Alba, u Hrvatskoj cete biti?', 'Zora'),
('CROATIAN', 'Stranke', 'Socijaldemokratska stranka Velike Britanije.', 'Laburisticka stranka'),
('CROATIAN', 'Strategije', 'Munjeviti rat.', 'Blitzkrieg'),
('CROATIAN', 'Strip', '"Tko vrijedi, leti, tko leti, vrijedi, tko ne leti,...', 'ne vrijedi'),
('CROATIAN', 'Stripovi', 'Autor Strumpfova.', 'Peyo'),
('CROATIAN', 'Strojarstvo', 'Energetski stroj za pretvaranje kineticke energije strujanja u mehanicki rad?', 'Turbina'),
('CROATIAN', 'Studenti', 'Student pred zavrsetkom studija.', 'Apsolvent'),
('CROATIAN', 'Sumarstvo', 'Izuzetno kvalitetno drvo indijskog hrasta.', 'Tikovina'),
('CROATIAN', 'Svemir', 'Erupcija velike mase plinova na povrsini Sunca.', 'Protuberanca'),
('CROATIAN', 'Talijanski', 'Bez.', 'Senza'),
('CROATIAN', 'Talijanski jezik', 'Cvor, uzao.', 'Grop'),
('CROATIAN', 'Teatar', 'Popularno kazaliste u epohi Fadila Hadjica.', 'Jazavac'),
('CROATIAN', 'Tehnicki', 'Izumio (usavrsio) parni stroj?', 'James Watt'),
('CROATIAN', 'Tehnika', 'Hidroplan umjesto stajnog trapa ima...?', 'Plovni trap'),
('CROATIAN', 'Tehnologija', 'Aleksandrijski izumitelj prve naprave pokretane parom.', 'Heron'),
('CROATIAN', 'Telefonija', 'Pozivni broj Turkmenistana?', '993'),
('CROATIAN', 'Televizija', 'ALFov mracni predmet zelja, macak...?', 'Srecko\nLucky'),
('CROATIAN', 'Televizijski citati', '"Will i Grace":" Jezik je nastao kad su se rodili ruzni ljudi koje je trebalo..."?', 'Ogovarati'),
('CROATIAN', 'Tenis', 'Argentinski tenisac armenskog podrijetla.', 'David Nalbandian'),
('CROATIAN', 'Terorizam', '9/1 2004. je za Ruse u Sjevernoj Osetiji spomen na gotovo 400 poginulih (vecinom djece), u cecenskoj opsadi i kaoticnom oslobadjanju zatocenih osnovnoskolaca u gradu...', 'Beslanu'),
('CROATIAN', 'Test brzine', '"6345532412" napisati obrnuto', '2142355436'),
('CROATIAN', 'Tiskarstvo', 'Prvi otisak, primjerak prvog izdanja (ili: prvotni rukopis)?', 'Arhetip'),
('CROATIAN', 'Titule', 'Biskup ili nadbiskup koji nije uzdignut do ranga kardinala?', 'Monsinjor'),
('CROATIAN', 'Tolkien', '"Bijeli grad", prijestolnica Gondora?', 'Minas Tirith'),
('CROATIAN', 'Topcoder', 'Koliki najmanje mora biti rating za crvenu boju?', '2200'),
('CROATIAN', 'Tradicija', 'Staro dalmatinsko jelo Poljicke republike, sastojci: razvuceno tijesto, blitva, kapula i premaz od ulja s cesnjakom.', 'Soparnik'),
('CROATIAN', 'Transport', 'Buducnost transporta: kombinacija leteceg tanjura i amfibije, konstrukcija aeronautickog inzenjera Paula Mollera...', 'M200G Volantor'),
('CROATIAN', 'Trgovina', 'Cin kojim se obavlja nagodba; trgovacki ugovor?', 'Transakcija'),
('CROATIAN', 'Turcizam', 'Dilber.', 'Ljubavnik'),
('CROATIAN', 'Turcizmi', 'Kredit, povjerenje.', 'Veresija'),
('CROATIAN', 'Turizam', 'Izmedju koja dva grada se vozi "Maraton ladja"?', 'Metkovic i Ploce\nMetkovica i Ploca'),
('CROATIAN', 'TV', 'Americka znanstveno - fantasticna serija, karakteristicna po tome sto je i prije samog pocetka snimananja imala zacrtanu cijelu pricu.', 'Babylon 5'),
('CROATIAN', 'TV serije', 'Lik iz "Mucki" karakteristican po svojoj bradi i "lovackim pricama"?', 'Ujak Albert'),
('CROATIAN', 'Ucenicki biseri', 'Grcki novac se zove ...', 'Drakula'),
('CROATIAN', 'Umijetnost', 'U kojem je slavnom pariskom kabareu Lautrec bio cest gost?', 'Moulin rouge'),
('CROATIAN', 'Umjetnici', 'Biokemicar i pisac sf romana, porijeklom zidov, rodjen u rusiji?', 'isaac asimov'),
('CROATIAN', 'Umjetnost', '"Doruckom na travi" i "Olimpijom" sokirao je cijeli Pariz.', 'Edouard Manet'),
('CROATIAN', 'Umjetnost/Religija', 'Svetac kojega u likovnim umjetnostima prikazuju probodenog strjelicama?', 'Sebastijan'),
('CROATIAN', 'Urbanizam', 'Broj gradskih cetvrti Zagreba...', '17\nsedamnaest'),
('CROATIAN', 'Uredjaji', 'Sto mjeri kronometar', 'vrijeme'),
('CROATIAN', 'Ustanove', 'Amer. ustanova osnovana s namjerom posmrtnog odavanja pocasti zasluznim Amerikancima.', 'Hall of fame\nDvorana slave'),
('CROATIAN', 'Utjecaj reklama', '"MIlka": Samo ljubicaste krave su...?', 'Zdrave krave'),
('CROATIAN', 'Uzrecice', 'Avercenko:Sretni ljudi ne gledaju na...?', 'sat'),
('CROATIAN', 'V.I.P.', 'Betty Davis je jednom rekla za Joan Crawford: "Ona je spavala sa svim muskim glumcima iz MGM-a, osim sa......."?', 'lassie'),
('CROATIAN', 'Valute', 'Novac u Danskoj', 'Kruna'),
('CROATIAN', 'Veselice', 'Kartaska igra sa 2 snopa po 52 karte i 2 jokera.', 'Remi\nRummy'),
('CROATIAN', 'Vic', 'Gospodine, kada ste shvatili da ste krava ? - Davno, davno...kad sam jos bio... ?', 'tele'),
('CROATIAN', 'Vicevi', 'Idu dve cackalice ulicom i sretnu lizalicu. Kaze jedna onoj drugoj: ...', 'vidi onog glavonje'),
('CROATIAN', 'Vina', 'Jedna od najpoznatijih sorti grozdja, francuskog podrijetla?', 'Cabernet Sauvignon'),
('CROATIAN', 'Vjerovanja', 'Obicaj stvaranja buke u novogodisnjoj noci vuce korijene iz vjerovanja da se tako ...?', 'Tjeraju demoni'),
('CROATIAN', 'Vjetrovi', 'topao i suh vjetar u alpama', 'fen'),
('CROATIAN', 'Voce', 'Azijska kruska ili ...', 'Nashi'),
('CROATIAN', 'Vojska', 'Baloni vezani celicnom uzadi iznad gradova kojima se ometalo bombardiranje u 2. svj. ratu?', 'Barazni baloni'),
('CROATIAN', 'Vozila', 'Amfibijsko vozilo s trupom nalik na camac, pogonjeno avionskim propelerom, koje se najvise koristi u mocvarama?', 'Hidrokopter'),
('CROATIAN', 'Vrazje stvari', 'Neprijateljska sila kojom upravlja Sotona.?', 'Magog'),
('CROATIAN', 'Vrijeme', 'Dan poslije tekuceg dana.', 'Sutra'),
('CROATIAN', 'Vrsta poligamije', 'bracna veza muskarca s vise zena.', 'Poliginija'),
('CROATIAN', 'Vrste', 'Ribe preci kopnenih kraljeznjaka.', 'Resoperke'),
('CROATIAN', 'XXX', 'Stil bicevanja u sadomazohizmu kod kojeg dva bicevaoca naizmjence ritmicki i po odredjenom obrascu bicuju zrtvu?', 'firentinsko bicevanje'),
('CROATIAN', 'Za inteligentne', 'koliko je 10 i 30?', 'pola jedanaest'),
('CROATIAN', 'Zabava', 'Amatersko pjevanje na javnom mjestu uz snimljenu glazbu?', 'Karaoke'),
('CROATIAN', 'Zafrkancija', 'Kratica ofr.?', 'obicni fizicki radnik'),
('CROATIAN', 'Zagonetka', '5 golubova na grani. Dodje lovac i pogodi jednog puskom. Koliko je golubova ostalo na grani?', '0\nnijedan'),
('CROATIAN', 'Zagonetke', 'Crven jarac po pecini skace.', 'Jezik'),
('CROATIAN', 'Zagreb', 'Sumovita pjesacka staza koja spaja Tuskanac i Cmrok.', 'Dubravkin put'),
('CROATIAN', 'Zajednice', 'Brak.', 'Matrimonij'),
('CROATIAN', 'Zakon', 'Pismeno podnijeta optuzba', 'optuznica'),
('CROATIAN', 'Zakoni', 'Koja drzava SADa je predlozila zakon da broj Pi iznosi 3?', 'indiana'),
('CROATIAN', 'Zamljopis', 'Poznato skijaliste u Italiji?', 'Santa Caterina'),
('CROATIAN', 'Zanimljivo', 'Po njemu, spoznaja je moguca samo ako se oslobodimo ukorijenjenih predrasuda i laznih pojmova (idola). On je jedan od osnivaca modernog materijalizma?', 'Francis Bacon'),
('CROATIAN', 'Zanimljivost', '"Everyman" (engleska alegorijska igra iz 15.st.) kod nas se prevela kao...?', 'Svatkovic'),
('CROATIAN', 'Zanimljivosti', '"Guinnessova knjiga rekorda" drzi rekord kao ...', 'Najcesce ukradena knjiga iz knjizara'),
('CROATIAN', 'Zdravlje', 'Izlucevina zdrijelnih zlijezda pcela radilica, koristi se za poboljsanje imuniteta?', 'maticna mlijec'),
('CROATIAN', 'Zemljopis', '"Biser" sjevernog Jadrana?', 'Opatija'),
('CROATIAN', 'Zemljopis i nogomet', 'Povijesna pokrajina u jugozapadnoj Francuskoj i prezime poznatog engleskog nogometasa', 'Gascoigne'),
('CROATIAN', 'Zemljopis/fizika', 'Vjetar od 12 bofora i jacine 118-133km/h.', 'Orkan'),
('CROATIAN', 'Zene izumitelji', '1950.g. Marion Donovan izumila je nepromocive ...', 'Jednokratne pelene'),
('CROATIAN', 'Zgrade', 'Koje godine je dovrsen Empire State Building?', '1931'),
('CROATIAN', 'Ziva istina', 'Sa godinama koji se organ brze smanjuje u muskraca nego u zena?', 'Mozak'),
('CROATIAN', 'Zivotinja', 'Autohtona vrsta macke porijeklom iz Sibira, zelenih ociju i kratke, mekane dlake sa srebrnasto plavim odsjajem.', 'Ruska plava macka\nRussian Blue cat'),
('CROATIAN', 'Zivotinje', '"Lastin rep" ili "Admiral"?', 'Leptir'),
('CROATIAN', 'Znacenja', 'Sto znaci rijec kamikaza?', 'Poslanici bozjeg vjetra'),
('CROATIAN', 'Znanost', '1940 godine pocela je proizvodnja antibiotika u motrenim uvijetima pomocu cega?', 'mikroorganizama'),
('CROATIAN', 'Znanost/knjizevnost', 'Perzijski matematicar i pjesnik ("Rubaije")?', 'Omar Hajjam'),
('CROATIAN', 'Znanosti', 'Ihtiologija proucava sto...?', 'ribe'),
('CROATIAN', 'Znanstvenici', 'Englez, otkrivac Havajskog otocja i Australije koji je dokazao da je Antarktik okruzen Oceanom?', 'James Cook'),
('CROATIAN', 'Zodijak', 'Jedini znak koji ne predstavlja zivo bice je ...?', 'vaga'),
('CROATIAN', 'Zoologija', '"Papucari" morskog svijeta (zenke snesu jaja u njihove trbusne vrecice, a oni nose trudnocu i radjaju zive mlade).', 'Silo i morski konjic'),
('CROATIAN', 'Zrakoplovstvo', 'Americki lovac dugoga dometa i jedan od najuspjesnijih tipova za borbu 1-na-1 u II. sv. ratu.', 'P-51 Mustang'),
('ENGLISH', '-isms', 'a diseased condition resulting from the use of beverages such as whiskey.', 'alcoholism'),
('ENGLISH', '007', 'how does bond introduce himself on meeting someone for the first time', 'my name is bond, james bond'),
('ENGLISH', '11', '37 pm in military time is how many hours', '2337'),
('ENGLISH', '1960''s', 'who recorded "groovin''"?', 'young rascals'),
('ENGLISH', '1961 movies', 'name one of the major stars in "the errand boy"', 'jerry lewis'),
('ENGLISH', '1964', 'He was appointed Deputy Commander of Military Assistance', 'westmoreland'),
('ENGLISH', '1980s GrabBag', 'C. American strongman who appeared on a Time cover entitled "The Drug Thugs"', 'general manuel noriega'),
('ENGLISH', '1984 movies', 'name one of the major stars in "silence of the heart"?', 'mariette hartley'),
('ENGLISH', '1985 movies', 'name one of the major stars in "sins of the fathers"?', 'julie christie'),
('ENGLISH', '1990', 'what is the #5 us daily newspaper with 1,117,376 average circulation', 'new york times'),
('ENGLISH', '1991 gulf war', 'what missiles did the allies use to intercept iraqi scuds', 'patriots'),
('ENGLISH', '1992', 'What Biblical disease did 39 Texans come down with in 1992', 'leprosy'),
('ENGLISH', '1992 Movies', 'Name one of the major stars in "Diggstown"', 'james woods'),
('ENGLISH', '1993', 'name one of the major stars in the film cliffhanger', 'john lithgow'),
('ENGLISH', '1993 Movies', 'Name one of the major stars of "Indecent Proposal"', 'woody harrelson\ndemi moore'),
('ENGLISH', '1993 The Year', '$20 billion of financial aid went to this nation.', 'russia'),
('ENGLISH', '1997 Great Events', 'Stock markets on this continent plunged in October.', 'asia'),
('ENGLISH', '19th Cent Art', '"Death of Marat" and "Oath of the Horatii", two of his better known works', 'jacques-louis david'),
('ENGLISH', '5', '45 pm in military time is how many hours', '1745'),
('ENGLISH', '50s', 'Born in 1959, she was the actress possessed by the Devil in The Exorcist.', 'blair'),
('ENGLISH', '50s Authors', 'A Death in the FamilyXX: A Death in the Family', 'james agee'),
('ENGLISH', '60"s tv', 'what was "gentle ben"?', 'bear'),
('ENGLISH', '60''s tv', 'what bank did the "beverly hillbillies" swear by?', 'commerce bank'),
('ENGLISH', '60s', '1964 release was the most successful Disney film to date.', 'mary poppins'),
('ENGLISH', '60s Authors', 'Goodbye, Columbus', 'phillip roth'),
('ENGLISH', '7', '25 pm in military time is how many hours', '1925'),
('ENGLISH', '70''s Name the Artist', '(don''t fear) the reaper', 'blue oyster cult'),
('ENGLISH', '70s', 'Angola won its independence fromthem in 1975.', 'portugal'),
('ENGLISH', '70s Authors', 'A Book of Common Prayer', 'joan didion'),
('ENGLISH', '80''s Films', 'a dirty mind is a terrible thing to waste', 'steel magnolias'),
('ENGLISH', '80''s Name the Artist', 'he''ll never love you (like i do)', 'freddie jackson'),
('ENGLISH', '80s', 'G.D. Searle & Co put this brand sweetener on the market in 1983.', 'nutrasweet'),
('ENGLISH', '80s Films', '"In the Southeast, they say if you want to go to heaven, you have to change planes in Atlanta."', 'Accidental Tourist'),
('ENGLISH', '90''s Name the Artist', '3 a.m. eternal', 'the klf');
INSERT INTO `questions_bak` (`language`, `theme`, `question`, `answers`) VALUES
('ENGLISH', 'Abbreviations', 'cricket''s lbw', 'leg before wicket'),
('ENGLISH', 'Academy Awards', 'best song in 1962', 'days of wine and roses'),
('ENGLISH', 'Acronym', '<BEG>', 'big evil grin'),
('ENGLISH', 'Acronym soup', 'http', 'hyper text transfer protocol'),
('ENGLISH', 'Acronyms', 'waves', 'women accepted for volunteer emergency service'),
('ENGLISH', 'Actor', 'arnold schwarzenegger bought the first hummer manufactured for civilian use when', '1992'),
('ENGLISH', 'Ad Jingles', 'Ask any mermaid you happen to see, what''s the best tuna', 'chicken of the sea'),
('ENGLISH', 'Ad Slogans', '"Just for the taste of it"', 'diet coke'),
('ENGLISH', 'Ads', '"Your baby''s comfort" begins with this.', 'luvs'),
('ENGLISH', 'Advertising', 'According to Nintendo, the capital of Ohio is this.', 'mario'),
('ENGLISH', 'Advertising Slogans', 'don''t leave home without it', 'american express'),
('ENGLISH', 'Alcatraz', 'how many wardens did the prison have in its 29 years', 'four'),
('ENGLISH', 'Alcohol', 'According to the Old Testament, he planted the first vineyard', 'noah'),
('ENGLISH', 'Algebra', 'Define the value of X: -10x - 19 = 19 - 8x', '-19'),
('ENGLISH', 'Alternative Art', 'A dark style of futuristic art, gun- and death-laden.', 'heavy metal'),
('ENGLISH', 'Alternative Music', 'Finish this song title: ''Heaven or ___ _____''', 'las vegas'),
('ENGLISH', 'American Authors', 'Among his short stories are "The Open Boat" and "The Blue Hotel".', 'Stephen Crane'),
('ENGLISH', 'American Cartoonists', 'Cartoon created by Dale Messick', 'brenda starr'),
('ENGLISH', 'Americanisms', 'Britains say ''tarmac''; Americans say ________.', 'runway'),
('ENGLISH', 'Analogies', 'Anson MacDonald : Stranger in a Strange Land :: Edith Van Dyne : <blank>', 'the wizard of oz'),
('ENGLISH', 'Analogy', 'goose - geese as passerby - ___________', 'passersby'),
('ENGLISH', 'Anatomy', 'Your ____ holds your head to your shoulders.', 'neck'),
('ENGLISH', 'Animal Trivia', '---------- and short-tailed shrews get by on only two hours of sleep a day.', 'elephants'),
('ENGLISH', 'Animals', 'Does a giraffe have a voice?', 'yes'),
('ENGLISH', 'Anime', 'What city does _Evangelion_ take place in', 'tokyo 3'),
('ENGLISH', 'Aptronyms', 'best little hairhouse in town', 'hairdresser'),
('ENGLISH', 'Art', 'what henri charriere best seller describes his escape from devil''s island', 'papillon'),
('ENGLISH', 'Artists', '"A beautiful bunch of ripe bananas"', 'harry belafonte'),
('ENGLISH', 'Artists Hometowns', 'Firehose', 'san pedro'),
('ENGLISH', 'Arts', 'how many attended the march hare''s tea party', 'four'),
('ENGLISH', 'Asimov Anthony', '"The Game" involved a matrix of what size', '4x4'),
('ENGLISH', 'Astrology', 'If you were born on 01 April what star sign (Zodiac) would you be', 'aries'),
('ENGLISH', 'Astronomy', 'A heavenly body moving under the attraction of the Sun and consisting of a nucleus and a tail is a(n) _______.', 'comet'),
('ENGLISH', 'athletics', 'who won a consecutive 122 races at 400m hurdles between 1977 ďż˝ 1987', 'edwin moses'),
('ENGLISH', 'Aussie Slang', '''ave a Gander', 'have a look'),
('ENGLISH', 'Author', '"A Raisin in the Sun"', 'hansberry'),
('ENGLISH', 'Authors', 'a study in scarlet', 'sir arthur conan doyle'),
('ENGLISH', 'AUTHORS/POETS', 'Who wrote Illiad', 'Alexander Pope'),
('ENGLISH', 'balistics', 'what does the acronym bar stand for', 'browning automatic rifle'),
('ENGLISH', 'ballet', 'leap in which dancer rapidly strikes heels together in air.', 'entrechat'),
('ENGLISH', 'Barbie', 'Barbie variety with suntanned skin', 'malibu'),
('ENGLISH', 'Barbie Dolls', 'Barbie is actually derived from this German doll, intended as a sexual gag', 'lilli'),
('ENGLISH', 'Baseball', 'Hank Aaron received more of what than any other person', 'personal mail'),
('ENGLISH', 'Basketball', 'the Chicago ______', 'bulls'),
('ENGLISH', 'Battlestar Galactica', 'what was the name of the human leader of the cylons', 'baltar'),
('ENGLISH', 'Be Prepared', 'Large, regional division of the BSA. Analogous to the OA''s lodge.', 'council'),
('ENGLISH', 'Bear bryant remark', 'a tie is like kissing your', 'sister'),
('ENGLISH', 'Beer', 'Beers made with top fermenting yeasts, usually at warmer temperatures.', 'ale'),
('ENGLISH', 'Bestsellers', 'According to Erma Bombeck, this is the second oldest profession', 'motherhood'),
('ENGLISH', 'Beverly Hills 90210', 'what was the name of brandon''s first car', 'mondale'),
('ENGLISH', 'Biblical Character', 'Apostle who replaced Judas', 'matthias'),
('ENGLISH', 'Biochemistry', 'This poisonous, oily liquid occurs in tobacco leaves.', 'nicotine'),
('ENGLISH', 'Biology', 'Every human has one of these on their tummies.', 'navel'),
('ENGLISH', 'BIRTHSTONES', 'April', 'diamond'),
('ENGLISH', 'Bloom County', 'Name of the groundhog', 'portnoy'),
('ENGLISH', 'BONANZA', 'What clothing did Little Joe usually wear', 'green jacket & grey pants\ngreen jacket grey pants'),
('ENGLISH', 'Bond', 'What was the first James Bond film?', 'Dr. No'),
('ENGLISH', 'Books', 'Alice in Wonderland was created by him (pen name).', 'lewis carroll'),
('ENGLISH', 'Books for the Bored', 'In which series of books would you find the fortress of Salamandastron', 'redwall'),
('ENGLISH', 'Booze Grabbag', 'A.K.A juniper juice?', 'gin'),
('ENGLISH', 'Booze Names', '1 1/2 oz. light rum, 1 lime, powdered sugar, fruit juice, blend w/crushed ice', 'daiquiri'),
('ENGLISH', 'Botany', 'The practice of joining the parts of two plants to make them grow as one is called ________.', 'grafting'),
('ENGLISH', 'British Monarchs', 'Queen Victoria was born in this year.', '1819'),
('ENGLISH', 'Bursery Rhymes', 'Jack and Jill went up a ____ to fetch a pail of water', 'hill'),
('ENGLISH', 'Callendar', 'How many days where there in 1976', '366'),
('ENGLISH', 'canadian', 'a person loyal to the british crown in the 1780''s', 'loyalist'),
('ENGLISH', 'Canadianisms', 'Finish the quote: "The Mounties always".', 'get their man'),
('ENGLISH', 'Candy', 'Candy bar named for a celestial object.', 'milky way'),
('ENGLISH', 'Capital cities', 'Finland', 'helsinki'),
('ENGLISH', 'Cars', '"The Death Car of Sarajevo", killed 15 people over 12 years, including him.', 'archduke ferdinand'),
('ENGLISH', 'Cartoon Sidekicks', 'Buttons', 'mindy'),
('ENGLISH', 'Cartoon Trivia', 'An adventurous penguin named Tennessee Tuxedo had a sidekick named _______', 'chumley'),
('ENGLISH', 'Category', '1980s GrabBag : He lost the 1977 NYC mayoral bid before taking successful aim at Albany', 'mario cuomo'),
('ENGLISH', 'Celebrity', 'The director of Jaws, Raiders of the Lost Ark', 'stephen spielberg'),
('ENGLISH', 'Celebrity Lovers', 'It took a while, but Donald Trump finally married her', 'marla maples'),
('ENGLISH', 'celtic mythology', 'trjstan''s lover', 'isolde'),
('ENGLISH', 'Cereal Appeal', '"Don''t worry, unless they''re strange, your kids will eat them!"', 'life'),
('ENGLISH', 'Character Creators', 'Anna Karenina', 'leo tolstoy'),
('ENGLISH', 'Cheers', 'what was the name of the bar that always played practical jokes on the gang at cheers', 'gary''s old time tavern'),
('ENGLISH', 'Chekhov Quotations', '"Doctors can bury their mistakes, Architects can only advise their clients to plant vines."', 'Frank Lloyd Wright'),
('ENGLISH', 'Chemical Symbols', 'Ca', 'Calcium'),
('ENGLISH', 'Chemistry', 'Hydrogen Hydroxide is more commonly known as what', 'water'),
('ENGLISH', 'Childrens Literature', '"Escape to Witch Mountain" was written by', 'alexander key'),
('ENGLISH', 'Chinese', 'What do you call a Chinese sailing ship', 'junk'),
('ENGLISH', 'chinese mythology', 'the monkey god was captured in', 'buddha''s palm'),
('ENGLISH', 'Chips', '1980''s Apple II 6502 ran at 2MHz. Where is 1995''s PowerPC 604 clocked at', '150mhz'),
('ENGLISH', 'Christmas', 'Name the loner rebel reindeer with the red shiny nose.', 'rudolph'),
('ENGLISH', 'Cigarettes', 'Brand named for a motorcycle make.', 'harley davidson'),
('ENGLISH', 'city nicknames', 'where is motown', 'detroit'),
('ENGLISH', 'Civil War', 'CSA General nicknamed "Old Rosy"', 'william starke rosecrans'),
('ENGLISH', 'Classic Board Games', '------- & Righter (former US owners of Scrabble rights)', 'selchow'),
('ENGLISH', 'Classical Music', '"A musical joke" refers to:', 'A Sextet by Mozart'),
('ENGLISH', 'Cliches', 'A ----- of one''s imagination.', 'figment'),
('ENGLISH', 'Clive Barker', 'Featured in both "The Last Illusion" and The Books of the Art.', 'harry damour'),
('ENGLISH', 'Clothes', '1990s slang for very short cutoff jeans.', 'daisy dukes'),
('ENGLISH', 'Cocktails', 'bourbon, sugar & mint make a(n) ___________', 'mint julep'),
('ENGLISH', 'Colors in the title', 'eiffel 65', 'blue'),
('ENGLISH', 'Comic Strip Trivia', 'What comic strip is set at Camp Swampy', 'beetle bailey'),
('ENGLISH', 'comics', 'cable''s full real name', 'nathan christopher summer'),
('ENGLISH', 'Complete the line', '"Step on a crack"', 'break your back'),
('ENGLISH', 'Complete the proverb', '''The sweetest wine makes the sharpest...''', 'vinegar'),
('ENGLISH', 'Complete this phrase', 'Friends, Romans,', 'countrymen'),
('ENGLISH', 'Computer Science', 'That big square thing you''re staring at right now is called a _______', 'monitor'),
('ENGLISH', 'computer term', 'what does ram stand for', 'random access memory'),
('ENGLISH', 'Computers', '1kB equals how many bytes', '1024'),
('ENGLISH', 'Confuscious Say', 'A girl''s best ------ is her ''lie''ability.', 'asset'),
('ENGLISH', 'Contemporary Authors', 'Another Country, Go Tell It on the Mountain', 'james baldwin'),
('ENGLISH', 'country', 'land of the thousand lakes', 'finland'),
('ENGLISH', 'Couples', 'Abe Lincoln and ____ ____', 'mary todd'),
('ENGLISH', 'Crime Stories', 'A is for this', 'alibi'),
('ENGLISH', 'Crime Writers', '>From Russia, With Love', 'fleming'),
('ENGLISH', 'currency', 'where would "taka" be used?', 'bangladesh'),
('ENGLISH', 'Cyberpunk', 'A program that runs in the background of a decker''s OS', 'daemon'),
('ENGLISH', 'Dandy Candy', '"There''s no wrong way of eating" this.', 'reeses peanut butter cups'),
('ENGLISH', 'DC Comics', 'Broke Batman', 'bane'),
('ENGLISH', 'DC Secret Identities', 'Arthur Curry', 'aquaman'),
('ENGLISH', 'Deaths 91 to 92', 'Hall of Famer and 2nd baseman for Pennant-winning 1941 Brooklyn Dodgers', 'billy herman'),
('ENGLISH', 'Definitions', '-isms: A diseased condition resulting from the use of beverages such as whiskey.', 'alcoholism'),
('ENGLISH', 'Devils Dictionary', 'A familiar kitchen-garden vegetable about as large and wise as a man''s head', 'cabbage'),
('ENGLISH', 'Disney', '"Hair Facts" from the Broadway version of "Beauty and The Beast": Four characters'' wigs are made of -------------: Mrs. Potts, Lumiere, Madame de la Grande Bouche, and the Sugar Bowl from "Be Our Guest."', 'yak hair'),
('ENGLISH', 'Disneyworld', 'What is one of the main entertainment areas called', 'magic kingdom'),
('ENGLISH', 'Dr Seuss', 'He owned a bottomless pool', 'mcelligot'),
('ENGLISH', 'dragonlance', 'who was the sister of raistlin and caramon?', 'kitiara'),
('ENGLISH', 'Drama', 'Our Town" is a play by whom', 'thornton wilder'),
('ENGLISH', 'Driving', 'what area is identified by the letter V', 'vatican city'),
('ENGLISH', 'Duffy', 'A Confederacy of Dunces', 'john kennedy toole'),
('ENGLISH', 'Easy People', 'For what was Dr. Crippen hanged?', 'murdering his wife'),
('ENGLISH', 'Easy question', 'type the alphabet', 'abcdefghijklmnopqrstuvwxyz'),
('ENGLISH', 'elvis', 'how many songs were recorded for the movie "follow that dream"', 'seven\n7'),
('ENGLISH', 'Emoticons', '(h_h)', 'happiness'),
('ENGLISH', 'English charts', 'Clive Dunn had a hit called Grandad in which year', '1971'),
('ENGLISH', 'Entertainment', '1959 thriller has Cary Grant as an ad man mistaken for a secret agent', 'north by northwest'),
('ENGLISH', 'epl', 'what is manchester united''s home stadium called', 'old trafford'),
('ENGLISH', 'Family Ties', 'who was alex p. keaton''s idol', 'richard nixon'),
('ENGLISH', 'Famous Animals', 'Blondie''s dog.', 'daisy'),
('ENGLISH', 'Famous birthday', '25 March 1947', 'elton john'),
('ENGLISH', 'Famous Canadians', 'Canadian Prime Minister who was on American Immigration''s blacklist.', 'pierre elliot trudeau'),
('ENGLISH', 'Famous Celebrities', 'Of which country is Juan Carlos king?', 'spain'),
('ENGLISH', 'Famous Gills', '50''s era baseball player. Same last name as Craig, formerly of NBA''s Bulls.', 'gil hodges'),
('ENGLISH', 'Famous Last Words', 'Are you sure the -------- is off', 'power'),
('ENGLISH', 'Famous People', 'Nicky Clarke''s name is famous in which fashion field', 'hairdressing'),
('ENGLISH', 'Famous Quotes', '"This is a sharp medicine, but a sure cure for all diseases."', 'sir walter raleigh'),
('ENGLISH', 'Fantasy', 'What is a sorcerer who deals in black magic called', 'necromancer'),
('ENGLISH', 'Fashion', 'Artificial structure worn to extend shirts behind.', 'bustle'),
('ENGLISH', 'Fast Food', 'A girl with pig tails, and a white-haired man represent this chain.', 'wendys'),
('ENGLISH', 'Fast food franchise', 'Taco ____', 'bell'),
('ENGLISH', 'Fictional Detectives', 'Agatha Christie''s elderly female crimesolver.', 'miss marple'),
('ENGLISH', 'Fill in', 'adding insult to____', 'injury'),
('ENGLISH', 'fill in the blank', 'chang and eng were the most famous', 'siamese twins'),
('ENGLISH', 'film', 'what was the name of princess leia''s home planet', 'alderon'),
('ENGLISH', 'films', 'who directed the movie broadway danny rose', 'woody allen'),
('ENGLISH', 'Films Quotes', 'a dirty mind is a terrible thing to waste', 'steel magnolias'),
('ENGLISH', 'finance', 'what do you call the stock market that is on the rise', 'bull market'),
('ENGLISH', 'Fish', 'How many eggs can a bluegill lay', '40,000'),
('ENGLISH', 'FLOWERS', 'What flower is associated with the month of April', 'sweet pea'),
('ENGLISH', 'Food', 'A food labelled "Florentine" is prepared with this.', 'spinach'),
('ENGLISH', 'Food and Drink', 'At which stage of a meal would you have an hors d''oeuvre?', 'beginning'),
('ENGLISH', 'Football', 'the Chicago ______', 'bears'),
('ENGLISH', 'French', 'done and past arguing about', 'fait accompli'),
('ENGLISH', 'French Food AKA', 'Clarified double-strength brown stock', 'consomme'),
('ENGLISH', 'Friends', 'what did phoebe promise to give chandler if he never smoked again', '$7,000\nseven thousand dollars'),
('ENGLISH', 'Full House', 'uncle jesse had a last name before it became katsopolis what was it', 'cochran'),
('ENGLISH', 'Fun', 'Cocktails: Bourbon, sugar and mint make a(n) ___________.', 'mint julep'),
('ENGLISH', 'Gals Named Mary', '"Mary, Mary, ----- --------, --- ---- ---- ------ ----?" (omit comma)', 'quite contrary how does your garden grow'),
('ENGLISH', 'Games', 'A bridge hand with no cards in one suit is said to have a _______.', 'void'),
('ENGLISH', 'Gay Issues', 'A lesbian kiss on what ABC sitcom caused an uproar?', 'roseanne'),
('ENGLISH', 'General', '12 letter word: fancy name for fireworks', 'pyrotechnics'),
('ENGLISH', 'General Knowledge', 'Although it doesn''t sound like a dog, ____dust is ornamental wood chips often placed in flowerbeds.', 'bark'),
('ENGLISH', 'Generation X Toys', 'Atari competitor that featured better graphics.', 'intellevision'),
('ENGLISH', 'Geographic', 'The first country along the great circle route due south from San Francisco', 'canada'),
('ENGLISH', 'Geographic Trivia', 'The aurora borealis is most commonly observed in which country', 'canada'),
('ENGLISH', 'Geographic Tyrrivia', 'Excluding Alaska, the American state with the lowest population density is?', 'wyoming'),
('ENGLISH', 'Geography', '"Honolulu" means -----', 'sheltered harbor'),
('ENGLISH', 'Geogrpahy', 'Name the capital city of Utah.', 'salt lake city'),
('ENGLISH', 'Geology', 'Earth''s outer layer of surface soil or crust is called the _______.', 'lithosphere'),
('ENGLISH', 'Gilligans Island', 'What is the Professor''s only concern about his most brilliant idea', 'if it will work'),
('ENGLISH', 'Grab Bag', 'Weekly Radio show taped in West Virginia', 'mountain stage'),
('ENGLISH', 'Grabbag', 'New England state mentioned in a Mark Twain title, he also lived there', 'connecticut'),
('ENGLISH', 'Grammy Awards', 'What album by Barbra Streisand won the grammy in 1963', 'barbra streisand album'),
('ENGLISH', 'Greek Mythology', 'Brother Of Prometheus, Son Of The Titan Lapetus', 'Atlas'),
('ENGLISH', 'Gulf war', 'what missiles did the allies use to intercept iraqi scuds', 'patriots'),
('ENGLISH', 'Hahaha', 'This normally has 4 legs and your butt is parked in it right now.', 'chair'),
('ENGLISH', 'happy days', 'joanie''s first date was with one of fonzie''s cousins. what was his name', 'spike'),
('ENGLISH', 'hawaii', 'what is the nickname of the island lanai', 'pineapple island'),
('ENGLISH', 'Hirtory', 'Name the first black nation to gain freedom from European colonial rule.', 'haiti'),
('ENGLISH', 'History', 'beginning in the 1820s, who from the southeastern united states were relocated to indian territory over numerous routes', 'the five civilized tribes'),
('ENGLISH', 'Histroy', 'What did President J. Buchanan not have', 'a wife'),
('ENGLISH', 'Hitchhikers Guide', 'A mind-boggingly stupid, but very very ravenous, animal.', 'ravenous bugblatter beast of traal'),
('ENGLISH', 'Hobbies & Leisure', 'A Royal Flush is the best hand you can get in which game', 'poker'),
('ENGLISH', 'Hockey', 'One of three 20 minute segments making up the game', 'period'),
('ENGLISH', 'Hogan''s heroes', 'what was cpl. louis lebeau''s nickname', 'cockroach'),
('ENGLISH', 'Holidays', 'Derived from Eostre, the dawn goddess of Anglo-Saxon myth.', 'easter'),
('ENGLISH', 'Hollywodd', 'She played the lead role in "Coal Miner''s Daughter".', 'sissy spacek'),
('ENGLISH', 'Hollywood', 'Actor: _______ Borgnine.', 'ernest'),
('ENGLISH', 'honeymooners', 'name the restaurant everyone eats at special occasions?', 'hong kong gardens'),
('ENGLISH', 'Hsitory', 'Who discovered the tomb of Tutenkhamen', 'Howard Carter'),
('ENGLISH', 'i love lucy', 'what was ricky''s profession', 'band leader'),
('ENGLISH', 'Identify', '"If you''ve got the time, we''ve got the beer"', 'miller beer'),
('ENGLISH', 'In Common', 'Belly, fever, journalism, pages', 'yellow'),
('ENGLISH', 'In the Star Trek', 'Deep Space Nine series, name the Ferengi owner of the bar on Deep Space Nine', 'quark'),
('ENGLISH', 'indian mythology', 'creator of the universe', 'brahma'),
('ENGLISH', 'indiana jones', 'how many shankara stones did indy deliver', 'only one\none'),
('ENGLISH', 'Internet domains', 'identify the country: es', 'spain'),
('ENGLISH', 'Intl Beers', 'Admeeral Tyeyskoye', 'Russia'),
('ENGLISH', 'IRC', 'What three letters are overly used to indicate "Laugh Out Loud"', 'lol'),
('ENGLISH', 'Irish', 'The Irish name for Ireland', 'eire'),
('ENGLISH', 'Isms', 'Public ownership of the basic means of production, distribution, and exchange', 'socialism'),
('ENGLISH', 'Italian', 'variety of cabbage with a green flower head', 'broccoli'),
('ENGLISH', 'Junk Food', 'British: fish and _____', 'chips'),
('ENGLISH', 'Kids in the Hall', 'A Mark McKinney character says "I''m _ your head!"', 'crushing'),
('ENGLISH', 'knight', 'he sang to entertain the crowds at wimbledon 1996, when rain interrupted play.', 'sir cliff richard'),
('ENGLISH', 'Knight Rider', 'what''s the real last name of michael knight', 'long'),
('ENGLISH', 'Kulture', 'She wrote "Valley of the Dolls".', 'jaqueline susann'),
('ENGLISH', 'Landmarks', 'what theme park is located in buena park, california', 'knotts berry farm'),
('ENGLISH', 'Langauge', 'Many Meanings: Fuel, vapor, flattulence, helium. What is it', 'gas'),
('ENGLISH', 'Language', 'Multiple Meanings: Drinking utensils or sight-enhancers.', 'glasses'),
('ENGLISH', 'Languages', '"Entre nous" means __________.', 'between ourselves'),
('ENGLISH', 'Lateral Thinking', 'For example: 88 = P K - Answer 88 Piano Keys: -  Question:  1 = W on a U', 'Wheel on a Unicycle'),
('ENGLISH', 'Laverne & Shirley', 'what was laverne''s favorite drink', 'milk and pepsi'),
('ENGLISH', 'Lead Singers', '10,000 manaics', 'natalie merchant'),
('ENGLISH', 'Legal terms', 'a crime more serious than a misdemeanor', 'felony'),
('ENGLISH', 'Legend', 'Say''s the goblin? "This shot shall be just as sweet as ____"', 'pie'),
('ENGLISH', 'Length', '220 yards = 1 ______', 'furlong'),
('ENGLISH', 'License Plates', 'What does 1MORDR say when given a first diagnosis', 'one more doctor'),
('ENGLISH', 'Literary Characters', 'Also know as Mistress Betty this English adventuress is a creation of Defoe', 'moll flanders'),
('ENGLISH', 'Literature', '"The Diary of Anne Frank" was first published in English under what title', 'the diary of a young girl'),
('ENGLISH', 'Logic', 'You are in a room where all walls face south. A bear walks by. What color is it?', 'white'),
('ENGLISH', 'Lyrics', 'a cloud appears above your head a beam of light comes shining down on you', 'i ran'),
('ENGLISH', 'm-a-s-h', 'who gave radar his exam for his high school diploma?', 'colonel blake'),
('ENGLISH', 'M.A.S.H', 'what are col blake''s two favorite outdoor sports', 'fishing and golf\nfishing golf'),
('ENGLISH', 'Made In Canada', 'City where Motley Crue recorded Dr. Feelgood.', 'vancouver'),
('ENGLISH', 'Magazines', 'This magazine chronicled the Man of Bronze and the Fabulous Five.', 'doc savage'),
('ENGLISH', 'Magnum PI', 'rick was not rick''s real name. what was his real name', 'orville wright '),
('ENGLISH', 'Mash', 'what was radar o''reilly''s real first name', 'walter'),
('ENGLISH', 'Math', 'what is 1 days and 2 hours in hours', '26'),
('ENGLISH', 'Mathematics', 'A line drawn from an angle of a triangle to the mid-point of the opposite side is a(n) -----.', 'median'),
('ENGLISH', 'McDonalds', 'After the first cup of this beverage, refills are usually free.', 'coffee'),
('ENGLISH', 'Measurement', '15 pounds per square inch equal', 'one atmosphere'),
('ENGLISH', 'Medicine', 'A baby doctor is a _________.', 'pediatrician'),
('ENGLISH', 'Meteorology', 'If the groundhog sees his shadow on Feb. 2, there will be how many more weeks of bad weather', 'six'),
('ENGLISH', 'Military', '11:00am in military time is how many hours?', '1100'),
('ENGLISH', 'Mindbender', 'if a plane crashes on the border where do they bury the survivors', 'nowhere'),
('ENGLISH', 'Misc', 'what was known as the englishman''s drink', 'port'),
('ENGLISH', 'Misc Games', 'a.k.a a pair of aces & a pair of eights', 'dead mans hand'),
('ENGLISH', 'Miscellaneous', '"7x" was used to refer to the secret ingredient of what drink', 'coca cola'),
('ENGLISH', 'mlb', 'bill veeck wanted to move his st louis browns to this city in 1953.', 'los angeles'),
('ENGLISH', 'MONEY', 'What is 2 Grand + A Monkey + A Score ďż˝', '2520'),
('ENGLISH', 'monopoly railroads', 'reading, pennsylvanie, b & o, & _____?', 'short line'),
('ENGLISH', 'Moscow 1980 Olympics', 'How many BRONZE medals were won by: Australia', '5'),
('ENGLISH', 'Motorsport', 'what is the name of the grand prix race track in germany', 'hockenheim'),
('ENGLISH', 'Movie Lines', 'Go ahead, take a good look. When you''re through, we''ll continue.', 'man without a face'),
('ENGLISH', 'Movies', 'Name one of the major stars in diggstown', 'james woods'),
('ENGLISH', 'Movies /TV', 'Who starred in the film "The Ten Commandments"', 'charlton heston'),
('ENGLISH', 'Movies/ TV', 'What was the title of Henry Fonda''s last film', 'on golden pond'),
('ENGLISH', 'munich 1958', 'who was england''s youngest ever footballer till 1998 and possessed one of the most powerful shots in the history of football, but died of his injuries after the fateful crash', 'duncan edwards'),
('ENGLISH', 'Music', '"... and I yearn for some cerebral fix..."', 'in the flat field'),
('ENGLISH', 'Music artist', 'Who did "Stranger in a Strange Land" in 1971', 'leon russell'),
('ENGLISH', 'music artists', 'who did "are you experienced" in 1967?', 'jimi hendrix'),
('ENGLISH', 'Music Term', '(1) The cancelling of a flat or sharp of a note or key indicated by a sign beside the note; (2) A trumpet or horn, etc. not having any valves or keys.', 'natural'),
('ENGLISH', 'musical groups', 'commander cody & his _____', 'lost planet airmen'),
('ENGLISH', 'musical term', 'what is fortissimo', 'very loud'),
('ENGLISH', 'Mythology', 'The sea gods had a three-pronged spear called a(n) ________.', 'trident'),
('ENGLISH', 'Name That Celebrity', 'Author of The Hobbit and The Lord of the Rings', 'J.R.R. Tolkien'),
('ENGLISH', 'Name That Dog Breed', '___', 'affenpinscher'),
('ENGLISH', 'Name That Tune', 'all day starring at the ceiling making friends with shadows on the walls', 'unwell'),
('ENGLISH', 'Name the Actor', 'who played ashley wilkes', 'leslie howard'),
('ENGLISH', 'Name the Artist', 'a different beat', 'boyzone'),
('ENGLISH', 'Name the artist/band', '(Something Inside) So Strong', 'labi siffre'),
('ENGLISH', 'Name The Author', 'Fear Of Flying, How To Save Your Own Life', 'jong'),
('ENGLISH', 'Name The Poet', 'A Red, Red Rose', 'robert burns'),
('ENGLISH', 'Name The Year', '"60 Minutes" premiers.', '1968'),
('ENGLISH', 'Name Their Job', 'Barry Commoner', 'scientist'),
('ENGLISH', 'Name Their Job 2', 'Billie Jean King', 'tennis'),
('ENGLISH', 'Name Their Job1', 'Swifty Lazar', 'hollywood agent'),
('ENGLISH', 'Name their Network', 'alan king', 'comedy central'),
('ENGLISH', 'Names for numbers', '1 followed by 42 zeroes', 'tredecillion'),
('ENGLISH', 'National Anthems', '...At your feet, two oceans roar for your noble mission.', 'panama'),
('ENGLISH', 'National capitals', 'Costa Rica', 'san jose'),
('ENGLISH', 'Natural History', 'Name the largest of the dinosaurs.', 'brachiosaurus'),
('ENGLISH', 'Nature', 'A "sirocco" refers to a type of __________.', 'wind'),
('ENGLISH', 'Navy ranks', 'stars a ''rear admiral'' has', '2'),
('ENGLISH', 'ncaa', 'in what year was the first men''s volleyball championship held?', '1970'),
('ENGLISH', 'NetHack', 'Never put this wand in your Bag of Holding!', 'cancellation'),
('ENGLISH', 'Neture', 'What do oak trees grow from', 'acorns'),
('ENGLISH', 'Night Court', 'harry had a statue of what animal in his office', 'armidillo'),
('ENGLISH', 'norse mythology', 'father of thor', 'odin'),
('ENGLISH', 'Not Telling ;-)', 'What would be kept in an "aviary"', 'bird'),
('ENGLISH', 'Not telling ;-P', 'What are these: chrysolite, beryl, jasper, and tourmaline', 'gem'),
('ENGLISH', 'Novelty Songs', '1987 spoof of Star Trek which hit #1 in the UK', 'star trekkin'),
('ENGLISH', 'Numbers', 'how is the year 2000 written in roman numerals', 'mm'),
('ENGLISH', 'Nursery Rhymes', 'Name the nursery rhyme mother whos last name is that of a bird', 'goose'),
('ENGLISH', 'Nusic', 'Irish Rovers recorded a song in 1968 about what animal of folklore', 'unicorn'),
('ENGLISH', 'Oddities', 'Beethoven reportedly poured this over his head to stimulate his brain', 'water'),
('ENGLISH', 'Old Trek', 'At age seven Spock was betrothed to who', 't''pring'),
('ENGLISH', 'Olympics', 'Atlanta 1996 : This countries medal tally was: 0 Gold, 0 Silver, 1 Bronze, 1 in Total', 'india'),
('ENGLISH', 'On This Day', '01 April 1970 ---------- release hoax they are having dual sex change operations', 'john & yoko'),
('ENGLISH', 'Onassis driving', 'what country is identified by the letters ma', 'morocco'),
('ENGLISH', 'One Liners', 'how many californians to screw in a light bulb one to do it and four to', 'share the experience'),
('ENGLISH', 'Original Titles', '1805 by Leo Tolstoy', 'war and peace'),
('ENGLISH', 'Peanuts Comics', 'Schroeder''s favorite composer.', 'beethoven'),
('ENGLISH', 'People', 'American author best known for Moby Dick.', 'herman melville'),
('ENGLISH', 'Periodic Table', 'what is Np', 'neptunium'),
('ENGLISH', 'phonetic alphabet', 'c', 'charlie'),
('ENGLISH', 'photography', 'what''s the acronym for slr?', 'single lens reflex'),
('ENGLISH', 'Physics', 'The energy which a body possesses by virtue of its motion is called ________.', 'kinetic'),
('ENGLISH', 'Pinball', '1994 Data East game based on the pinball-themed Broadway play', 'tommy'),
('ENGLISH', 'Pizza Stuff', 'A green variety of these are often used as fishing bait.', 'shrimp'),
('ENGLISH', 'Poem Authors', 'He wrote "Adonais" upon hearing of John Keats'' death.', 'percy shelley'),
('ENGLISH', 'Poet', 'A Dream Deferred', 'langston hughes'),
('ENGLISH', 'POETS', 'Who wrote Kabla Kahn', 'samuel taylor coleridge'),
('ENGLISH', 'Politics', 'For what does O.P.E.C. stand', 'the organization of petroleum exporting countries'),
('ENGLISH', 'Pop Culture', 'What does S.C.A stand for (Hint: medieval re-enactment)', 'society for creative anachronism'),
('ENGLISH', 'Pop Kulture', 'He holds the world record for the most broken bones (443)', 'evel knievel'),
('ENGLISH', 'Potpourri', 'A person who speaks Faroese most likely lives in this country.', 'denmark'),
('ENGLISH', 'Princess Bride', 'Domingo Montoya''s profession', 'swordmaker'),
('ENGLISH', 'Proverb', 'the early bird __________', 'catches the worm'),
('ENGLISH', 'Psychology', '----- is the fear of beards', 'pognophobia'),
('ENGLISH', 'Puzzles', 'A butt holder or trash in pig latin', 'ashtray'),
('ENGLISH', 'Quick! Quick!', 'How is the state of Mississippi spelled', 'mississippi'),
('ENGLISH', 'Quotations', '" is not the absence of fear, but rather the judgement that something else is more important than fear."- Ambrose Redmoon', 'courage'),
('ENGLISH', 'Quotes', '"A cynic is someone who knows the price of everything and the value of nothing.', 'wilde'),
('ENGLISH', 'RADIO ALPHABET', 'What is the call sign for the letter A?', 'alfa'),
('ENGLISH', 'Regligion', 'On which mountain did Moses receive the Ten Commandments', 'sinai'),
('ENGLISH', 'Relatives', 'Aeneas'' mom', 'aphrodite'),
('ENGLISH', 'Religion', 'Followers of the Unification Church are called ________.', 'moonies'),
('ENGLISH', 'remember when', 'who was john deutschendorf better known as', 'john denver'),
('ENGLISH', 'Robert Heinlein', 'Character who conquered old age in Time Enough For Love', 'lazarus long'),
('ENGLISH', 'Robin Hood', 'Prince of Thieves was released in what year', '1992'),
('ENGLISH', 'rock groups', 'bill haley & the _____?', 'comets'),
('ENGLISH', 'Roman numerals', 'what is equivalent of cc', '200'),
('ENGLISH', 'Romanian music', 'who performed "Ploaie in Luna Lui Martie"', 'paula selling'),
('ENGLISH', 'Say Cheese', 'Dutch origin; inedible casing; mild; appetizer, dessert.', 'edam'),
('ENGLISH', 'Saying', 'A bird in the hand is worth two in the', 'bush'),
('ENGLISH', 'Scents', 'Charlie and Jontue manufacturer', 'revlon'),
('ENGLISH', 'Sci Fi', 'A swarm of these were always floating around the Artificial Kid''s head.', 'cameras'),
('ENGLISH', 'Sci Fi Authors', '"Creator" of the Star Trek series', 'William Shatner'),
('ENGLISH', 'Science', 'A flat-bottomed conical laboratory flask with a narrow neck is called a(n) __________.', 'erlenmeyer'),
('ENGLISH', 'scottish', 'a "bairn" is a?', 'child'),
('ENGLISH', 'Scuba', 'if a marine animal cannot be identified, a diver should _____', 'avoid it completely'),
('ENGLISH', 'Second City', 'Arequipa', 'peru'),
('ENGLISH', 'Second City 2', 'Antwerp', 'belgium'),
('ENGLISH', 'Seoul 1988 Olympics', 'How many BRONZE medals were won by: Argentina', '1'),
('ENGLISH', 'Shades Of Red', 'Animal that will "go down in history."', 'rudolph the red-nosed reindeer'),
('ENGLISH', 'Sherlock Holmes', '''The five orange pips'' saw Holmes oppose this racist organization', 'ku klux klan'),
('ENGLISH', 'Similes', 'as fit as a(n) __________', 'fiddle'),
('ENGLISH', 'similies', 'as happy as a', 'lark'),
('ENGLISH', 'Simon & Simon', 'what unusual thing did rick live in', 'in a boat'),
('ENGLISH', 'simpsons', 'from what country is groundskeeper willie from', 'scotland'),
('ENGLISH', 'Slang', 'A promiscuous woman', 'slapper'),
('ENGLISH', 'Smurfs', 'This is the youngest of all the smurfs.', 'baby smurf'),
('ENGLISH', 'Snow Crash', 'Name the book''s main character', 'hiro protagonist'),
('ENGLISH', 'Soccer', 'the New York _________.', 'cosmos'),
('ENGLISH', 'song artists', 'long john _____.', 'baldry'),
('ENGLISH', 'song title', 'ticket to _____.', 'ride'),
('ENGLISH', 'Space indiana jones', 'what did drinking from the grail "grant"', 'immortality'),
('ENGLISH', 'Spanish', 'How do you say "fifty"', 'cincuenta'),
('ENGLISH', 'Spell out', 'quasar', 'quasi stellar object'),
('ENGLISH', 'Spelling', 'what is the only 15 letter word that can be spelled without repeating a letter', 'uncopyrightable'),
('ENGLISH', 'Sport', 'Baseball: The Baltimore ________.', 'orioles'),
('ENGLISH', 'Sports', 'archie moore, was world champion in what sport from 1952-1962', 'boxing'),
('ENGLISH', 'Sports Actors', 'Besides Field of Dreams, what other baseball movie starred Kevin Costner', 'bull durham'),
('ENGLISH', 'star wars', 'name the underwater gungan city.', 'otoh gunga'),
('ENGLISH', 'stds9', 'what fairy tale character appeared in "if wishes were horses"?', 'rumplestilskin'),
('ENGLISH', 'Stephen King', 'Early novel turned screenplay starring Arnold Schwartzenegger', 'the running man'),
('ENGLISH', 'Stephen King''s', '" pet ________"', 'cemetary'),
('ENGLISH', 'sttng', 'alcohol that''s reproduced by the replicator', 'synthehol'),
('ENGLISH', 'sttos', 'capt james kirk had a son named', 'david marcus'),
('ENGLISH', 'Summertime', 'This is the sandy area nearest the ocean.', 'beach'),
('ENGLISH', 'Sydney 2000 Olympics', 'How many BRONZE medals were won by: Algeria', '3'),
('ENGLISH', 'Tea', 'Better teabags contain these small particles sifted out of better teas', 'fannings'),
('ENGLISH', 'technical theater', 'what''s the instantaneous killing of all stage lights', 'blackout'),
('ENGLISH', 'television', 'what was laverne''s last name on laverne and shirley?', 'defazio'),
('ENGLISH', 'tennis', 'acclaimed as the best swede to step on court since bjorn borg, and arguably the best serve-and-volleyer of all time', 'stefan edberg'),
('ENGLISH', 'The 80s', 'Argentina called them the Malvinas Islands, the British this.', 'falkland'),
('ENGLISH', 'The Bible', '"The Prodigal Son". What does "prodigal" mean', 'wasteful\nlavish'),
('ENGLISH', 'The Disney Afternoon', 'GT Name Goofy''s son.', 'max'),
('ENGLISH', 'The Equalizer', 'what did the hero (mccall) call his former superior from the agency', 'control'),
('ENGLISH', 'The Great Lakes are', 'Lake Superior, Lake Erie, Lake Huron, Lake Michigan & Lake', 'ontario'),
('ENGLISH', 'The Royal Family', 'Edward VIII''s title after his abdication.', 'duke of windsor'),
('ENGLISH', 'the simpsons', 'what is apu''s surname', 'nahasapheemapetilon'),
('ENGLISH', 'The Tick', '"Not baked goods professor, baked ____!"', 'bads'),
('ENGLISH', 'theater', 'who wrote "the importance of being earnest"', 'oscar wilde'),
('ENGLISH', 'Three''s Company', 'what city did the trio live in', 'santa monica'),
('ENGLISH', 'Tom Clancy', 'How does NSA Cutter avoid responsibility in "Clear and Present Danger"', 'suicide'),
('ENGLISH', 'Toys', 'Board game involving rapid climbing and tragic sliding.', 'chutes and ladders'),
('ENGLISH', 'Toys Games', 'Charles Darrow based his game upon the 1904 "The Landlord''s Game".', 'monopoly'),
('ENGLISH', 'Translate', 'Latin "opus magnum"', 'masterpiece'),
('ENGLISH', 'Trees', 'which tree has catkins in the spring and edible nuts in the autumn', 'hazel'),
('ENGLISH', 'Triplets', 'Love, honor, and', 'obey'),
('ENGLISH', 'Trivia', '"7X" was used to refer to the secret ingredient of which drink', 'coca cola'),
('ENGLISH', 'True or false', '"Attila" mean "Iron Warrior"', 'false'),
('ENGLISH', 'tv', 'barbara bel geddes won a emmy in 1980 as outstanding lead actress in what drama series?', 'dallas'),
('ENGLISH', 'TV / Movie', 'What U.S. state is the setting for I Dream of Jeannie', 'florida'),
('ENGLISH', 'TV / Movies', '"-I''ve been giving myself shock treatments. -Up the voltage"', 'Real Genius'),
('ENGLISH', 'TV /Movies', 'Archie Leach was the central character in which British film', 'a fish called wanda'),
('ENGLISH', 'tv fill in the blank', 'alias smith & _____.', 'jones'),
('ENGLISH', 'TV Movies', 'Who finds a tiny flying saucer on her roof in The Invaders', 'agnes moorehead'),
('ENGLISH', 'TV Trivia', 'What did TVs IMF stand for', 'impossible mission forces'),
('ENGLISH', 'TV''s STTNG', 'In "Naked Now", who takes control of the Enterprise', 'wesley crusher'),
('ENGLISH', 'TV-Movies', 'back to the future contained this song by huey lewis and the news', 'the power of love'),
('ENGLISH', 'TV/ Movies', '"Cheers" took place in this city.', 'boston'),
('ENGLISH', 'TV/Movies', '"-God. How does a woman get so bitter? -Observation."', 'the opposite of sex'),
('ENGLISH', 'UK 50s', 'In 1959, which party was elected for the third time in a row in Britain?', 'conservative'),
('ENGLISH', 'UK City', 'Largest Nuclear Naval Base', 'Plymouth'),
('ENGLISH', 'UK Roulette', 'If You Bet ďż˝5 On Red & ďż˝5 On Black, What Is The Only Number That Prevents You From "Breaking Even"', '0'),
('ENGLISH', 'UnScramble this Word', 'a ! h m w', 'wham!'),
('ENGLISH', 'Us capitals', 'alabama', 'montgomery'),
('ENGLISH', 'US CITY NICKNAMES', 'What city is the City of Brotherly Love', 'philadelphia'),
('ENGLISH', 'US slang', 'a person who habitually takes the drugs freebase or crack', 'basehead'),
('ENGLISH', 'Useless Facts', '------- was the first European country to establish a system for health insurance for its workers in 1888.', 'germany'),
('ENGLISH', 'Useless Info', 'big mac jingle', 'two all beef patties, speical sauce, lettuce, cheese, pickles, onions, on a sesame seed bun'),
('ENGLISH', 'Useless Trivia', '"Crack" gets its name because it ---------- when you smoke it.', 'crackles'),
('ENGLISH', 'Vampires', 'Favourite place to sleep (and it''s portable!)', 'coffin'),
('ENGLISH', 'VCRs', 'DSS stands for this (Hint:Audio related)', 'dolby surround sound'),
('ENGLISH', 'VH1', 'This sexy swimsuit model hosted a ''Body Language'' special', 'kathy ireland'),
('ENGLISH', 'Video Games', '''Secret of Evermore'' was entirely produced in which country?', 'U.S.A.\nusa\nAmerica\nUnited States'),
('ENGLISH', 'War', '1950-1953', 'Korea\nKorean'),
('ENGLISH', 'What cat sniffed', '"Cute rots the intellect"', 'garfield'),
('ENGLISH', 'What oath begins', 'I swear by Apollo', 'the hippcratic oath'),
('ENGLISH', 'What riddle asked', '"what is it that walks on four legs, then on two legs, & then on three"', 'the riddle of the sphinx'),
('ENGLISH', 'What song exclaims', '"You can even eat the dishes"', 'candy man'),
('ENGLISH', 'what spiritual ends', '"and the walls came tumblin'' down"?', 'joshua fit the battle of jericho'),
('ENGLISH', 'Which have teeth', 'toads or frogs', 'frogs'),
('ENGLISH', 'who claimed "my name', 'jose jimenez"', 'bill dana'),
('ENGLISH', 'who exclaimed', '"holy barracuda"?', 'robin'),
('ENGLISH', 'who owns', 'almond joy candy', 'hershey'),
('ENGLISH', 'who pined', '"but, soft what light through yonder window breaks', 'romeo'),
('ENGLISH', 'who said', '"honey, i forgot the duck"', 'ronald reagan'),
('ENGLISH', 'Who warned', '"there''s a cancer growing on the presidency"', 'john dean iii'),
('ENGLISH', 'who wrote "2001', 'a space odyssey"', 'arthur c clarke'),
('ENGLISH', 'Who Wrote It', 'Who wrote ''Chopsticks''', 'arthur de lulli'),
('ENGLISH', 'Who wrote the opera', 'The Merry Widow', 'franz lehar'),
('ENGLISH', 'Who''s the Boss', 'what was samantha''s license plate on her first car', 'sam''s car'),
('ENGLISH', 'Wild Flowers', 'What''s blue, comes out in spring, and smells like hyacinth', 'bluebells'),
('ENGLISH', 'wizard of oz', 'what was the tin man going to ask the wizard for', 'heart\na heart'),
('ENGLISH', 'Word pairs', 'ball & ________', 'chain'),
('ENGLISH', 'Words containing for', 'many trees', 'forest'),
('ENGLISH', 'world cup (soccer)', 'most goals scored (13) in the 1958 cup was by', 'just fontaine'),
('ENGLISH', 'World Of Disney', 'On what New Orleans Square (Disneyland) ride do you travel up a waterfall', 'pirates of the caribbean'),
('ENGLISH', 'X-Files', 'what''s mulder''s nickname', 'spooky'),
('ENGLISH', 'X-Men Comics', 'Gahck battled wolverine here', 'savage land'),
('ENGLISH', 'zodiac', 'the ram is', 'aries');